### ISSUE TITLE
Loki sink not working properly in 0.22.*

### ISSUE THREAD

**Issue by tesharp** [vectordotdev/vector#13417]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

If the input for loki sink submits metric events it will fail in 0.22.*. This worked in earlier releases as Loki sink would only process the log events and ignore metrics. So could send metrics and logs through same transforms and connect to different sinks that would only process the events the sink could handle.

The problem seems to be related to this change in `sink\loki\config.rs:145`: 

```rust
fn input(&self) -> Input {
    Input::new(self.encoding.config().input_type())
}
```

which previously returned `Input:log()`. However, input_type() of encoding can return both log and metric as valid inputs for the sink. In my case using `codec: text` which returns both as valid and then it tries to process metric and panics.

Tried to change back to `Input:log()` as it was previously to verify that it fixed the problem.

### Configuration

```text
sources:
  internal_metrics:
    type: internal_metrics
    scrape_interval_secs: 15

sinks:
  loki:
    type: loki
    inputs:
    - internal_metrics
    endpoint: "http://loki:3100"
    tenant_id: "{{ tags.tenant }}"
    remove_timestamp: false
    out_of_order_action: accept
    encoding:
      codec: text
      timestamp_format: rfc3339
    labels:
      job: "{{ tags.job }}"
```

### Version

0.22.3

### Debug Output

```text
thread 'vector-worker' panicked at 'Failed type coercion, Metric(Metric { series: MetricSeries { name: MetricName { name: "http_client_requests_sent_total", namespace: Some("vector") }, tags: Some({"method": "GET"}) }, data: MetricData { timestamp: Some(2022-07-01T19:17:48.608531Z), kind: Absolute, value: Counter { value: 1.0 } }, metadata: EventMetadata { value: Object({}), secrets: {}, finalizers: EventFinalizers([]), schema_definition: Definition { collection: Collection { known: {}, unknown: None }, meaning: {} } } }) is not a log event', lib\vector-core\src\event\mod.rs:90:18
stack backtrace:
2022-07-01T19:17:48.646299Z ERROR http: vector::internal_events::http_client: HTTP error. error=error trying to connect: dns error: No such host is known. (os error 11001) error_type="request_failed" stage="processing"
2022-07-01T19:17:48.646738Z ERROR vector::topology::builder: msg="Healthcheck: Failed Reason." error=Failed to make HTTP(S) request: error trying to connect: dns error: No such host is known. (os error 11001) component_kind="sink" component_type="loki" component_id=loki component_name=loki
   0:     0x7ff64f56c36f - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff64f56c36f - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff64f56c36f - std::sys_common::backtrace::_print_fmt
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:66
   3:     0x7ff64f56c36f - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:45
   4:     0x7ff64f58ef1a - core::fmt::write
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\fmt\mod.rs:1194
   5:     0x7ff64f5626f9 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\io\mod.rs:1655
   6:     0x7ff64f56ed6b - std::sys_common::backtrace::_print
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:48
   7:     0x7ff64f56ed6b - std::sys_common::backtrace::print
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:35
   8:     0x7ff64f56ed6b - std::panicking::default_hook::closure$1
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:295
   9:     0x7ff64f56e95e - std::panicking::default_hook
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:314
  10:     0x7ff64f56f361 - std::panicking::rust_panic_with_hook
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:698
  11:     0x7ff64f56f21d - std::panicking::begin_panic_handler::closure$0
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:588
  12:     0x7ff64f56cc77 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:138
  13:     0x7ff64f56eef9 - std::panicking::begin_panic_handler
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:584
  14:     0x7ff64f8d56d5 - core::panicking::panic_fmt
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\panicking.rs:143
  15:     0x7ff64e377b3e - enum$<vector_core::event::Event>::as_log
                               at D:\git\source\vector\lib\vector-core\src\event\mod.rs:90
  16:     0x7ff648dff011 - vector::sinks::loki::sink::EventEncoder::encode_event
                               at D:\git\source\vector\src\sinks\loki\sink.rs:208
  17:     0x7ff648193a45 - vector::sinks::loki::sink::impl$10::run_inner::async_fn$0::closure$0
                               at D:\git\source\vector\src\sinks\loki\sink.rs:389
```

**Comment by jszwedko** [comment]
Thanks for this detailed report @tesharp . We'll resolve it for the 0.23.0 we are planning for next week.
