### ISSUE TITLE
Vector API panics when it can't listen on its socket

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#14157]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When the Vector API is given a listening address that it can't actually listen on, due to either a permissions issue or address already in use, for example, it will panic its thread:
```
thread 'main' panicked at 'error binding to 127.0.0.1:1: error creating server listener: Permission denied (os error 13)', /home/bruce.guenter/.cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.3.2/src/server.rs:283:27
```
This does not show up as a normal `ERROR` message, and so is less visible than other messages.

We may want to consider if this should also be caught in order to shut down Vector due to the misconfiguration.

### Version

current `master` head

**Comment by spencergilbert** [comment]
> We may want to consider if this should also be caught in order to shut down Vector due to the misconfiguration.

IIRC any other listener already being taken in the configuration will stop Vector from starting - I'd expect the same behavior for the API 👍

**Comment by zamazan4ik** [comment]
@bruceg @spencergilbert I have started to investigate the issue and tried several other sources/sinks with bindings. I have got the following results.

For `http_server` with the configuration:
```
[sources.http_server]
type = "http_server"
address = "127.0.0.1:3"
encoding = "text"
```
I see the following Vector logs:
```
2022-11-02T16:30:25.362716Z  INFO source{component_kind="source" component_id=http_server component_type=http_server component_name=http_server}: vector::sources::util::http::prelude: Building HTTP server. address=127.0.0.1:3
thread 'vector-worker' panicked at 'called `Result::unwrap()` on an `Err` value: TcpBind { source: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } }', src/sources/util/http/prelude.rs:155:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-11-02T16:30:25.366173Z ERROR source{component_kind="source" component_id=http_server component_type=http_server component_name=http_server}: vector::topology: An error occurred that Vector couldn't handle: the task panicked and was aborted.
2022-11-02T16:30:25.375194Z  INFO vector: Vector has stopped.
2022-11-02T16:30:25.376770Z  INFO vector::topology::running: Shutting down... Waiting on running components. remaining_components="demo, my_sink_id" time_remaining="59 seconds left"
```
Vector have shut downed but with a panic. I guess it is not good.

For the `prometheus` sink with the following configuration:
```
[sinks.prometheus]
type = "prometheus_exporter"
inputs = [ "metrics" ]
address = "127.0.0.1:2"
default_namespace = "service"
```
I see the following Vector logs:
```
2022-11-02T16:35:20.729701Z ERROR vector::sinks::prometheus::exporter: Server bind error: TCP bind failed: Permission denied (os error 13).
```
Vector is **not** stopped automatically but does not panic.

@spencergilbert could you please suggest the source, where I can find an example for the case "if listen fails, Vector is turned off **gracefully** automatically" because I cannot find such an example.

**Comment by zamazan4ik** [comment]
I guess I have found a good example - `socket` source. For the config:
```
[sources.socket]
type = "socket"
address = "127.0.0.1:4"
max_length = 102_400
mode = "tcp"
```
I see these logs:
```
2022-11-02T16:44:51.634910Z ERROR source{component_kind="source" component_id=socket component_type=socket component_name=socket}: vector::internal_events::socket: Error binding socket. error=TCP bind failed: Permission denied (os error 13) error_code="socket_bind" error_type="io_failed" stage="receiving" mode=tcp internal_log_rate_limit=true
2022-11-02T16:44:51.635709Z ERROR source{component_kind="source" component_id=socket component_type=socket component_name=socket}: vector::topology: An error occurred that Vector couldn't handle: the task completed with an error.
```
Vector has stopped gracefully and automatically, without a panic.

Regarding the examples above, I guess they should be fixed as well.
