### ISSUE TITLE
Vector panics when metric is sent via `stdin` using `native_json` encoding

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#14754]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Discovered while troubleshooting https://github.com/vectordotdev/vector/issues/14693

I attempted to pass a metric using the `native_json` encoding for the `stdin` sink which caused a panic.

### Configuration

```text
sources:
  stdin:
    type: stdin
    decoding:
      codec: native_json
sinks:
  console:
    type: console
    inputs:
      - stdin
    target: stdout
    encoding:
      codec: json
```

### Version

vector 0.24.1

### Debug Output

```text
2022-10-06T17:00:17.878014Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info,kube=info"
2022-10-06T17:00:17.878066Z  INFO vector::app: Loading configs. paths=["/tmp/tmp.yaml"]
2022-10-06T17:00:17.879099Z  INFO vector::topology::running: Running healthchecks.
2022-10-06T17:00:17.879126Z  INFO vector::sources::file_descriptors: Capturing stdin.
2022-10-06T17:00:17.879204Z  INFO vector::topology::builder: Healthcheck: Passed.
2022-10-06T17:00:17.879262Z  INFO vector: Vector has started. debug="false" version="0.24.1" arch="aarch64" build_id="none"
2022-10-06T17:00:17.879281Z  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.
thread 'vector-worker' panicked at 'Failed type coercion, Metric(Metric { series: MetricSeries { name: MetricName { name: "pods", namespace: Some("kube_extra_metrics") }, tags: Some({"app": "log-collector", "base_name": "log-collector", "env": "stage", "environment": "stage", "has_cpu_limits": "false", "has_liveness_checks": "false", "has_mem_limits": "false", "has_readiness_checks": "false", "host": "i-02a3e40dc945f6d8f", "image_all_ecr": "true", "image_region": "us-west-2", "image_tag": "v0.9.1", "image_using_imager": "false", "k2_skip_checks": "false", "k2_version": "", "managed_by": "", "namespace": "monitoring", "parent": "daemonset", "phase": "running", "pool": "", "ready": "true", "region": "us-west-2", "shard": "", "status": "running", "version": "v0.9.1"}) }, data: MetricData { time: MetricTime { timestamp: Some(2022-10-03T18:59:50Z), interval_ms: None }, kind: Absolute, value: Gauge { value: 1.0 } }, metadata: EventMetadata { value: Object({}), secrets: {}, finalizers: EventFinalizers([]), schema_definition: Definition { event_kind: Kind { bytes: Some(()), integer: Some(()), float: Some(()), boolean: Some(()), timestamp: Some(()), regex: Some(()), null: Some(()), undefined: Some(()), array: Some(Collection { known: {}, unknown: Unknown(Infinite(Infinite { bytes: Some(()), integer: Some(()), float: Some(()), boolean: Some(()), timestamp: Some(()), regex: Some(()), null: Some(()), array: Some(()), object: Some(()) })) }), object: Some(Collection { known: {}, unknown: Unknown(Infinite(Infinite { bytes: Some(()), integer: Some(()), float: Some(()), boolean: Some(()), timestamp: Some(()), regex: Some(()), null: Some(()), array: Some(()), object: Some(()) })) }) }, metadata_kind: Kind { bytes: None, integer: None, float: None, boolean: None, timestamp: None, regex: None, null: None, undefined: None, array: None, object: Some(Collection { known: {}, unknown: Unknown(Exact(Kind { bytes: None, integer: None, float: None, boolean: None, timestamp: None, regex: None, null: None, undefined: Some(()), array: None, object: None })) }) }, meaning: {}, log_namespaces: {Vector, Legacy} } } }) is not a log event', lib/vector-core/src/event/mod.rs:102:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: vector_core::event::Event::as_mut_log
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
   5: futures_util::stream::stream::StreamExt::poll_next_unpin
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  11: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  12: tokio::runtime::task::harness::Harness<T,S>::poll
  13: std::thread::local::LocalKey<T>::with
  14: tokio::runtime::thread_pool::worker::Context::run_task
  15: tokio::runtime::thread_pool::worker::Context::run
  16: tokio::macros::scoped_tls::ScopedKey<T>::set
  17: tokio::runtime::thread_pool::worker::run
  18: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  19: tokio::runtime::task::harness::Harness<T,S>::poll
  20: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2022-10-06T17:00:17.898975Z  INFO vector_common::shutdown: All sources have finished.
2022-10-06T17:00:17.898985Z  INFO vector: Vector has stopped.
2022-10-06T17:00:17.898982Z ERROR source{component_kind="source" component_id=stdin component_type=stdin component_name=stdin}: vector::topology: An error occurred that Vector couldn't handle.
```

### Example Data

{ "metric": { "kind": "absolute", "name": "pods", "namespace": "kube_extra_metrics", "tags": { "app": "log-collector", "base_name": "log-collector", "env": "stage", "environment": "stage", "has_cpu_limits": "false", "has_liveness_checks": "false", "has_mem_limits": "false", "has_readiness_checks": "false", "host": "i-02a3e40dc945f6d8f", "image_all_ecr": "true", "image_region": "us-west-2", "image_tag": "v0.9.1", "image_using_imager": "false", "k2_skip_checks": "false", "k2_version": "", "managed_by": "", "namespace": "monitoring", "parent": "daemonset", "phase": "running", "pool": "", "ready": "true", "region": "us-west-2", "shard": "", "status": "running", "version": "v0.9.1" }, "timestamp": "2022-10-03T18:59:50Z", "gauge": { "value": 1 } } }

**Comment by vimalk78** [comment]
Hi,
I am interested in fixing this bug. I have sent a PR https://github.com/vectordotdev/vector/pull/14778. PTAL
