### ISSUE TITLE
Sometimes `payload` is zero length...

### ISSUE THREAD

**Issue by solidsnack** [vectordotdev/vector#15539]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

We are seeing this error occasionally when Vector starts up on a new server: `thread 'vector-worker' panicked at 'payload should never be zero length'` thrown from [`src/sinks/aws_cloudwatch_logs/request_builder.rs:109`](https://github.com/vectordotdev/vector/blob/9348d36b0826bf73eaf57e0875dcf0f5a1ef8aa0/src/sinks/aws_cloudwatch_logs/request_builder.rs#L109).

Could this be because we are forwarding Syslog in the text format and the check is for `message_bytes.len()`? The message is not the whole payload (it looks like checks in other files are for the payload as a whole, but I am not sure). Syslog message bodies are allowed to be zero length, and in the text format, the message is just the Syslog message body.

### Configuration

```text
[sources.systemd]
type = "journald"
current_boot_only = true

[sinks.cloudwatch]
type = "aws_cloudwatch_logs"
inputs = [ "systemd" ]
create_missing_group = true
create_missing_stream = true
group_name = "/computer"
stream_name = "{{ host }}"
compression = "gzip"
encoding= { codec = "text" }
```

### Version

vector 0.26.0 (x86_64-unknown-linux-gnu c6b5bc2 2022-12-05)

**Comment by bck01215** [comment]
Also experiencing on the kakfa sink

>  Jul 31 20:44:35 rva-cre02-kvm-prod01.ipa.liberty.edu vector[987406]: 2023-07-31T20:44:35.486232Z ERROR source{component_kind="source" component_id=gitlab component_type=docker_logs component_name=gitlab}: vector::internal_events::docker_logs: Received out of order log message. error_type="condition_failed" stage="receiving" container_id="8e1d4494e67380772d5750146ffab896b2b2004696a5cceec4b546aab74e7de0" timestamp="2023-07-31T20:44:34.063013027Z" internal_log_rate_limit=true
> Jul 31 20:44:35 rva-cre02-kvm-prod01.ipa.liberty.edu vector[987406]: 2023-07-31T20:44:35.486365Z ERROR source{component_kind="source" component_id=gitlab component_type=docker_logs component_name=gitlab}: vector::internal_events::docker_logs: Internal log [Received out of order log message.] is being suppressed to avoid flooding.
> Jul 31 20:44:35 rva-cre02-kvm-prod01.ipa.liberty.edu vector[987406]: thread 'vector-worker' panicked at 'payload should never be zero length', src/sinks/kafka/request_builder.rs:54:55

**Comment by leandrojmp** [comment]
Just had the same issue, also with the Kafka sink.

Is there any work around?

**Comment by leandrojmp** [comment]
This seems to wokr as a work around:

```
[transforms.valid_messages]
type = "remap"
inputs = ["input"]
source = """
    if .message == "" {
        abort
    }
"""
```

**Comment by vivithecanine** [comment]
Experiencing this with cloudwatch sink, workaround suggested in discord was to do the following

```[transforms.input_filter]
inputs = ["input"]
type   = "filter"
condition = '.message != ""'```

**Comment by Strange21** [comment]
Facing same issue while sending data from file to cloud watch sink.
here is the configuration 
```
[sources.my_file]
type = "file"
#data_dir = ""
include = ["/var/lib/vector/sample.log"]
start_at_beginning = true

[transforms.valid_messages]
type = "remap"
inputs = ["my_file"]
source = """
    if .message == "" {
        abort
    }
"""

[sinks.aws_cloudwatch_logs]
type = "aws_cloudwatch_logs"
inputs = ["valid_messages"]
compression = "none"
create_missing_group = true
create_missing_stream = true
group_name = "test_opentelemetry"
region = "ap-south-1"
stream_name = "test"
encoding.codec = "text"
inputs = ["input"]
type   = "filter"
condition = '.message != ""'
```
Even the work around is not working for my case.
