### ISSUE TITLE
logstash source - thread 'vector-worker' panicked

### ISSUE THREAD

**Issue by christophemorio** [vectordotdev/vector#16273]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

For each log received on logstash source, Vector returns error
```
thread 'vector-worker' panicked at 'assertion failed: min <= max', /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/cmp.rs:860:9
```

### Configuration

```text
# file: /etc/vector/main.yml:
---
sources:
  my_input:
    type: logstash
    address: 0.0.0.0:5044
sinks:
  my_sink:
    type: file
    inputs: [my_input]
    encoding:
      codec: json
    path: /tmp/vector-%Y-%m-%d.log
```

### Version

0.27.0

### Debug Output

```text
vector -vvv --config-dir /etc/vector/
2023-02-03T08:11:45.865316Z  INFO vector::app: Internal log rate limit configured. internal_log_rate_secs=10
2023-02-03T08:11:45.865487Z  INFO vector::app: Log level is enabled. level="vector=trace,codec=trace,vrl=trace,file_source=trace,tower_limit=trace,rdkafka=trace,buffers=trace,lapin=trace,kube=trace"
2023-02-03T08:11:45.865553Z  INFO vector::app: Loading configs. paths=["/etc/vector"]
2023-02-03T08:11:45.866231Z DEBUG vector::config::loading: No secret placeholder found, skipping secret resolution.
2023-02-03T08:11:45.866707Z DEBUG vector::topology::builder: Building new source. component=my_input
2023-02-03T08:11:45.866987Z DEBUG vector::topology::builder: Building new sink. component=my_sink
2023-02-03T08:11:45.867107Z  INFO vector::topology::running: Running healthchecks.
2023-02-03T08:11:45.867123Z DEBUG vector::topology::running: Connecting changed/added component(s).
2023-02-03T08:11:45.867143Z DEBUG vector::topology::running: Configuring outputs for source. component=my_input
2023-02-03T08:11:45.867166Z DEBUG vector::topology::running: Configuring output for component. component=my_input output_id=None
2023-02-03T08:11:45.867192Z DEBUG vector::topology::running: Connecting inputs for sink. component=my_sink
2023-02-03T08:11:45.867214Z DEBUG vector::topology::running: Adding component input to fanout. component=my_sink fanout_id=my_input
2023-02-03T08:11:45.867247Z DEBUG vector::topology::running: Spawning new source. key=my_input
2023-02-03T08:11:45.867250Z  INFO vector::topology::builder: Healthcheck passed.
2023-02-03T08:11:45.867275Z DEBUG vector::topology::running: Registered new allocation group. component_kind="source" component_type="logstash" component_id="my_input" group_id="2"
2023-02-03T08:11:45.867314Z TRACE vector::topology::running: Spawning new sink. key=my_sink
2023-02-03T08:11:45.867335Z DEBUG vector::topology::running: Registered new allocation group. component_kind="sink" component_type="file" component_id="my_sink" group_id="3"
2023-02-03T08:11:45.867373Z DEBUG source{component_kind="source" component_id=my_input component_type=logstash component_name=my_input}: vector::topology::builder: Source pump supervisor starting.
2023-02-03T08:11:45.867411Z DEBUG source{component_kind="source" component_id=my_input component_type=logstash component_name=my_input}: vector::topology::builder: Source pump starting.
2023-02-03T08:11:45.867445Z  INFO vector: Vector has started. debug="false" version="0.27.0" arch="x86_64" revision="5623d1e 2023-01-18"
2023-02-03T08:11:45.867449Z DEBUG source{component_kind="source" component_id=my_input component_type=logstash component_name=my_input}: vector::topology::builder: Source starting.
2023-02-03T08:11:45.867469Z  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.
2023-02-03T08:11:45.867572Z  INFO source{component_kind="source" component_id=my_input component_type=logstash component_name=my_input}: vector::sources::util::net::tcp: Listening. addr=0.0.0.0:5044
2023-02-03T08:11:45.867760Z DEBUG sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::topology::builder: Sink starting.
2023-02-03T08:11:45.868866Z TRACE vector: Beep.
2023-02-03T08:11:45.868886Z DEBUG sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::utilization: utilization=0.021053131831574978
2023-02-03T08:11:46.868964Z TRACE vector: Beep.
2023-02-03T08:11:47.868073Z TRACE vector: Beep.
2023-02-03T08:11:48.868162Z TRACE vector: Beep.
2023-02-03T08:11:49.868249Z TRACE vector: Beep.
2023-02-03T08:11:50.868357Z TRACE vector: Beep.
2023-02-03T08:11:50.868390Z DEBUG sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::utilization: utilization=0.0021053412659491895
2023-02-03T08:11:51.868319Z TRACE vector: Beep.
2023-02-03T08:11:52.868354Z TRACE vector: Beep.
2023-02-03T08:11:53.868483Z TRACE vector: Beep.
2023-02-03T08:11:54.868603Z TRACE vector: Beep.
2023-02-03T08:11:55.637143Z DEBUG source{component_kind="source" component_id=my_input component_type=logstash component_name=my_input}:connection{peer_addr=127.0.0.1:60158}: vector::sources::util::net::tcp: Accepted a new connection. peer_addr=127.0.0.1:60158
2023-02-03T08:11:55.637732Z TRACE source{component_kind="source" component_id=my_input component_type=logstash component_name=my_input}:connection{peer_addr=127.0.0.1:60158}: vector::internal_events::tcp: Bytes received. protocol="tcp" byte_size=472 peer_addr=127.0.0.1:60158
2023-02-03T08:11:55.637968Z TRACE source{component_kind="source" component_id=my_input component_type=logstash component_name=my_input}:connection{peer_addr=127.0.0.1:60158}: vector::internal_events::socket: Events received. count=5 byte_size=2296 mode=tcp
2023-02-03T08:11:55.638050Z TRACE source{component_kind="source" component_id=my_input component_type=logstash component_name=my_input}:connection{peer_addr=127.0.0.1:60158}: vector_buffers::topology::channel::limited_queue: Sent item.
2023-02-03T08:11:55.638073Z TRACE source{component_kind="source" component_id=my_input component_type=logstash component_name=my_input}:connection{peer_addr=127.0.0.1:60158}: vector_common::internal_event::events_sent: Events sent. count=5 byte_size=2616 output=_default
thread 'vector-worker' panicked at 'assertion failed: min <= max', /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/cmp.rs:860:9
stack backtrace:
   0:     0x55877f6abbde - std::backtrace_rs::backtrace::libunwind::trace::he615646ea344481f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55877f6abbde - std::backtrace_rs::backtrace::trace_unsynchronized::h6ea8eaac68705b9c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55877f6abbde - std::sys_common::backtrace::_print_fmt::h7ac486a935ce0bf7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55877f6abbde - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1b5a095d3db2e28f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55877ed308de - core::fmt::write::h445545b92224a1cd
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/fmt/mod.rs:1209:17
   5:     0x55877f677364 - std::io::Write::write_fmt::h55a43474c6520b00
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/io/mod.rs:1682:15
   6:     0x55877f6ad33f - std::sys_common::backtrace::_print::h65d20526fdb736b0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55877f6ad33f - std::sys_common::backtrace::print::h6555fbe12a1cc41b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55877f6ace3d - std::panicking::default_hook::{{closure}}::hbdf58083140e7ac6
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:267:22
   9:     0x55877f6ae0f6 - std::panicking::default_hook::haef8271c56b74d85
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:286:9
  10:     0x55877f6ae0f6 - std::panicking::rust_panic_with_hook::hfd45b6b6c12d9fa5
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:688:13
  11:     0x55877f6ada53 - std::panicking::begin_panic_handler::{{closure}}::hf591e8609a75bd4b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:577:13
  12:     0x55877f6ad9ec - std::sys_common::backtrace::__rust_end_short_backtrace::h81899558795e4ff7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x55877f6ad9c1 - rust_begin_unwind
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
  14:     0x55877e729252 - core::panicking::panic_fmt::h4235fa9b4675b332
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
  15:     0x55877e72934c - core::panicking::panic::h9ced3cf2f605ba6a
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:115:5
  16:     0x5587816b0a66 - core::ptr::drop_in_place<vector::sources::util::net::tcp::request_limiter::RequestLimiterPermit>::h84d9610340606322
  17:     0x558781a0bc6d - vector::sources::util::net::tcp::handle_stream::{{closure}}::h4ecc377796bd57d0
  18:     0x558781a09fc5 - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::ha3bc7d55fdaeb8aa
  19:     0x558781a08e6a - tokio::runtime::task::raw::poll::h0cc5754b9f175a89
  20:     0x55877f6ef8b2 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h2063adb645b203ed
  21:     0x55877f6f6e95 - tokio::runtime::task::raw::poll::he7bffe6f0c4c727e
  22:     0x55877f6d9009 - std::sys_common::backtrace::__rust_begin_short_backtrace::hfb0ab063688f3613
  23:     0x55877f6d8c8d - core::ops::function::FnOnce::call_once{{vtable.shim}}::h713fadf6047e137d
  24:     0x55877f6b0533 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4273f95ec44459b3
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:1987:9
  25:     0x55877f6b0533 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70f28fa4ddc269e5
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:1987:9
  26:     0x55877f6b0533 - std::sys::unix::thread::Thread::new::thread_start::h85a9c16b988e2bd0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys/unix/thread.rs:108:17
  27:     0x7f6442969ea7 - start_thread
  28:     0x7f644273da2f - clone
  29:                0x0 - <unknown>
2023-02-03T08:11:55.654271Z TRACE source{component_kind="source" component_id=my_input component_type=logstash component_name=my_input}: vector_core::fanout: Processing control message outside of send: ControlMessage::Add(ComponentKey { id: "my_sink" })
2023-02-03T08:11:55.654307Z TRACE source{component_kind="source" component_id=my_input component_type=logstash component_name=my_input}: vector_buffers::topology::channel::limited_queue: Sent item.
2023-02-03T08:11:55.654323Z TRACE source{component_kind="source" component_id=my_input component_type=logstash component_name=my_input}: vector_core::fanout: Sent item to fanout.
2023-02-03T08:11:55.654341Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector_common::internal_event::events_received: Events received. count=5 byte_size=2616
2023-02-03T08:11:55.654362Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::sinks::file: Computed next deadline. next_deadline=Instant { tv_sec: 6128659, tv_nsec: 602442764 } path=b"/tmp/vector-2023-02-03.log"
2023-02-03T08:11:55.654384Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::sinks::file: Opening new file. path=b"/tmp/vector-2023-02-03.log"
2023-02-03T08:11:55.654678Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::sinks::file: Writing an event to file. path=b"/tmp/vector-2023-02-03.log"
2023-02-03T08:11:55.654719Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector_common::internal_event::events_sent: Events sent. count=1 byte_size=521
2023-02-03T08:11:55.654729Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::internal_events::file: Bytes sent. byte_size=522 protocol="file" file=/tmp/vector-2023-02-03.log
2023-02-03T08:11:55.654757Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::sinks::file: Computed next deadline. next_deadline=Instant { tv_sec: 6128659, tv_nsec: 602838236 } path=b"/tmp/vector-2023-02-03.log"
2023-02-03T08:11:55.654772Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::sinks::file: Working with an already opened file. path=b"/tmp/vector-2023-02-03.log"
2023-02-03T08:11:55.654782Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::sinks::file: Writing an event to file. path=b"/tmp/vector-2023-02-03.log"
2023-02-03T08:11:55.654812Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector_common::internal_event::events_sent: Events sent. count=1 byte_size=522
2023-02-03T08:11:55.654820Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::internal_events::file: Bytes sent. byte_size=523 protocol="file" file=/tmp/vector-2023-02-03.log
2023-02-03T08:11:55.654836Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::sinks::file: Computed next deadline. next_deadline=Instant { tv_sec: 6128659, tv_nsec: 602917327 } path=b"/tmp/vector-2023-02-03.log"
2023-02-03T08:11:55.654845Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::sinks::file: Working with an already opened file. path=b"/tmp/vector-2023-02-03.log"
2023-02-03T08:11:55.654853Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::sinks::file: Writing an event to file. path=b"/tmp/vector-2023-02-03.log"
2023-02-03T08:11:55.654876Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector_common::internal_event::events_sent: Events sent. count=1 byte_size=522
2023-02-03T08:11:55.654885Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::internal_events::file: Bytes sent. byte_size=523 protocol="file" file=/tmp/vector-2023-02-03.log
2023-02-03T08:11:55.654898Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::sinks::file: Computed next deadline. next_deadline=Instant { tv_sec: 6128659, tv_nsec: 602980203 } path=b"/tmp/vector-2023-02-03.log"
2023-02-03T08:11:55.654907Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::sinks::file: Working with an already opened file. path=b"/tmp/vector-2023-02-03.log"
2023-02-03T08:11:55.654917Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::sinks::file: Writing an event to file. path=b"/tmp/vector-2023-02-03.log"
2023-02-03T08:11:55.654942Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector_common::internal_event::events_sent: Events sent. count=1 byte_size=522
2023-02-03T08:11:55.654951Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::internal_events::file: Bytes sent. byte_size=523 protocol="file" file=/tmp/vector-2023-02-03.log
2023-02-03T08:11:55.654971Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::sinks::file: Computed next deadline. next_deadline=Instant { tv_sec: 6128659, tv_nsec: 603053334 } path=b"/tmp/vector-2023-02-03.log"
2023-02-03T08:11:55.654983Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::sinks::file: Working with an already opened file. path=b"/tmp/vector-2023-02-03.log"
2023-02-03T08:11:55.654992Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::sinks::file: Writing an event to file. path=b"/tmp/vector-2023-02-03.log"
2023-02-03T08:11:55.655017Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector_common::internal_event::events_sent: Events sent. count=1 byte_size=523
2023-02-03T08:11:55.655028Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::internal_events::file: Bytes sent. byte_size=524 protocol="file" file=/tmp/vector-2023-02-03.log
2023-02-03T08:11:55.868350Z TRACE vector: Beep.
2023-02-03T08:11:55.868382Z DEBUG sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::utilization: utilization=0.0003371643367251264
2023-02-03T08:11:56.868481Z TRACE vector: Beep.
2023-02-03T08:11:57.868576Z TRACE vector: Beep.
2023-02-03T08:11:58.868717Z TRACE vector: Beep.
^C2023-02-03T08:11:58.871644Z  INFO vector: Vector has stopped.
2023-02-03T08:11:58.871766Z DEBUG source{component_kind="source" component_id=my_input component_type=logstash component_name=my_input}: vector::topology::builder: Source finished normally.
2023-02-03T08:11:58.871804Z DEBUG source{component_kind="source" component_id=my_input component_type=logstash component_name=my_input}: vector::topology::builder: Source pump finished normally.
2023-02-03T08:11:58.871838Z DEBUG source{component_kind="source" component_id=my_input component_type=logstash component_name=my_input}: vector::topology::builder: Source pump supervisor task finished normally.
2023-02-03T08:11:58.871863Z DEBUG sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::sinks::file: Receiver exhausted, terminating the processing loop.
2023-02-03T08:11:58.871873Z DEBUG sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::sinks::file: Closing all the open files.
2023-02-03T08:11:58.871917Z  INFO vector::topology::running: Shutting down... Waiting on running components. remaining_components="my_sink" time_remaining="59 seconds left"
2023-02-03T08:11:58.873528Z TRACE sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::sinks::file: Successfully closed file. path=b"/tmp/vector-2023-02-03.log"
2023-02-03T08:11:58.873570Z DEBUG sink{component_kind="sink" component_id=my_sink component_type=file component_name=my_sink}: vector::topology::builder: Sink finished normally.
```

### Prepare a pod vector + filebeat

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: vector-test
spec:
  containers:
    - name: vector
      command: [sleep]
      args: [infinity]
      image: timberio/vector:0.27.0-debian
      resources:
        limits:
          cpu: "1000m"  #  NO ISSUE IF SET TO 2000m
          memory: 512Mi
        requests:
          cpu: "250m"
          memory: 256Mi

    - name: filebeat
      command: [sleep]
      args: [infinity]
      image: docker.elastic.co/beats/filebeat:8.5.1
```

### Start Vector

```shell
kubectl exec -it vector- -c vector -- bash

rm /etc/vector/vector.toml

cat > /etc/vector/main.yml <<EOF
    sources:
      my_input:
        type: logstash
        address: 0.0.0.0:5044
    sinks:
      my_sink:
        type: file
        inputs: [my_input]
        encoding:
          codec: json
        path: /tmp/vector-%Y-%m-%d.log
EOF

export RUST_BACKTRACE=full
vector --config-dir /etc/vector/
```

### Start Filebeat

```shell
kubectl exec -it vector-test -c filebeat -- bash

bash -c "while true; do date --utc >> /tmp/test.log; sleep 5; done" &

cat > /tmp/filebeat.yml <<EOF
filebeat.inputs:
  - type: log
    paths: [/tmp/test.log]

output.logstash:
  hosts: "localhost"

logging:
  json: true
  level: "debug"
EOF

filebeat -e -E http.enabled=true -c /tmp/filebeat.yml
```

### Additional Context

This happens on Kubernetes when Vector container is set with `resources.limit.cpu: 1000m`, (while no issue for 2000m).

- other 0.27.0 images (alpine, distroless) have the same issue
- Vector version 0.26.0 have no issue

### References

#16095
#16103

**Comment by jhbigler** [comment]
I get a similar error when using the socket source in tcp mode. Seems to be an issue with how vector handles tcp servers

Config file:
```
[sources.tcp]
type = "socket"
address = "127.0.0.1:6001"
mode = "tcp"
request_buffer_bytes = 65536
connection_limit = 25

[sinks.stdout]
type = "console"
inputs = ["tcp"]
target = "stdout"

    [sinks.stdout.encoding]
    codec = "json"
```

Launch vector with:
`RUST_BACKTRACE=full vector -c vector.toml`

And in a separate shell, run:
`echo "Test Message" | ncat 127.0.0.1 6001`

I get the following error:
```
thread 'vector-worker' panicked at 'assertion failed: min <= max', /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/cmp.rs:860:9
stack backtrace:
   0:     0x55e4744b5bde - std::backtrace_rs::backtrace::libunwind::trace::he615646ea344481f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55e4744b5bde - std::backtrace_rs::backtrace::trace_unsynchronized::h6ea8eaac68705b9c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e4744b5bde - std::sys_common::backtrace::_print_fmt::h7ac486a935ce0bf7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55e4744b5bde - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1b5a095d3db2e28f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55e473b3a8de - core::fmt::write::h445545b92224a1cd
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/fmt/mod.rs:1209:17
   5:     0x55e474481364 - std::io::Write::write_fmt::h55a43474c6520b00
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/io/mod.rs:1682:15
   6:     0x55e4744b733f - std::sys_common::backtrace::_print::h65d20526fdb736b0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55e4744b733f - std::sys_common::backtrace::print::h6555fbe12a1cc41b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55e4744b6e3d - std::panicking::default_hook::{{closure}}::hbdf58083140e7ac6
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:267:22
   9:     0x55e4744b80f6 - std::panicking::default_hook::haef8271c56b74d85
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:286:9
  10:     0x55e4744b80f6 - std::panicking::rust_panic_with_hook::hfd45b6b6c12d9fa5
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:688:13
  11:     0x55e4744b7a53 - std::panicking::begin_panic_handler::{{closure}}::hf591e8609a75bd4b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:577:13
  12:     0x55e4744b79ec - std::sys_common::backtrace::__rust_end_short_backtrace::h81899558795e4ff7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x55e4744b79c1 - rust_begin_unwind
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
  14:     0x55e473533252 - core::panicking::panic_fmt::h4235fa9b4675b332
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
  15:     0x55e47353334c - core::panicking::panic::h9ced3cf2f605ba6a
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:115:5
  16:     0x55e4764baa66 - core::ptr::drop_in_place<vector::sources::util::net::tcp::request_limiter::RequestLimiterPermit>::h84d9610340606322
  17:     0x55e476abdc92 - vector::sources::util::net::tcp::handle_stream::{{closure}}::hed2ebdb3128222b8
  18:     0x55e476abc19b - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::h3236c1e0b83fd97a
  19:     0x55e476abaa8a - tokio::runtime::task::raw::poll::h1e7aef3d1bff35db
  20:     0x55e4744f98b2 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h2063adb645b203ed
  21:     0x55e474500e95 - tokio::runtime::task::raw::poll::he7bffe6f0c4c727e
  22:     0x55e4744e3009 - std::sys_common::backtrace::__rust_begin_short_backtrace::hfb0ab063688f3613
  23:     0x55e4744e2c8d - core::ops::function::FnOnce::call_once{{vtable.shim}}::h713fadf6047e137d
  24:     0x55e4744ba533 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4273f95ec44459b3
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:1987:9
  25:     0x55e4744ba533 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70f28fa4ddc269e5
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:1987:9
  26:     0x55e4744ba533 - std::sys::unix::thread::Thread::new::thread_start::h85a9c16b988e2bd0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys/unix/thread.rs:108:17
  27:     0x7f7fa9663ea5 - start_thread
  28:     0x7f7fa8e86b0d - clone
  29:                0x0 - <unknown>
```

**Comment by zamazan4ik** [comment]
@jhbigler Could you please try to reproduce it on the latest Vector (build it from scratch or just wait for the 0.28)? I cannot reproduce the crash on your example with the latest Vector on master on Mac M1 - the example works fine.

**Comment by richarddziennmi** [comment]
We have had similar problems in our setup when the servers have only 1VCPU assigned to them.

Using WinLogBeat to forward events to Vector via a local Logstash instance.

Vector config:
```
data_dir: 'C:\Program Files\vector\data'

log_schema:
  source_type_key: log.forwarder.source.type
  timestamp_key: event.created
  host_key: log.forwarder.source.host.name

sources:
  internal_logs:
    type: internal_logs

  winlogbeat:
    type: logstash
    address: "0.0.0.0:5044"

  httplocal:
    type: http_server
    address: "0.0.0.0:8080"
    decoding:
      codec: json
    framing:
      method: character_delimited
      character_delimited:
        delimiter: "\n"
    path_key: log.forwarder.source.http.path

transforms:

  fix_log_schema:
    type: remap
    inputs: 
      - httplocal
      - winlogbeat
    source: |
      if exists(."log.forwarder.source.type") { .log.forwarder.source.type = del(."log.forwarder.source.type") }
      if exists(."event.created") { .event.created = del(."event.created") }
      if exists(."log.forwarder.source.host.name") { .log.forwarder.source.host.name = del(."log.forwarder.source.host.name") }

  add_common_fields:
    type: remap
    inputs:
      - fix_log_schema
    source: |
      if !exists(.host.name) { .host.name = get_hostname() ?? "" }
      .platform = get_env_var!("PLATFORM")
      .network.vlan.name = get_env_var!("NETWORK_VLAN_NAME")
      .host.datacenter = get_env_var!("DATACENTER")
      .service.environment = get_env_var!("ENVIRONMENT")
      .log.forwarder.agent = "vector"
      .log.forwarder.host.name = get_hostname() ?? ""
      .log.forwarder.type = "local"

sinks:
  vector:
    type: vector
    inputs:
      - add_common_fields
    address: "log-aggregator.service.local:6000"
    buffer:
      type: disk
      max_size: 2147483648
    request:
      retry_max_duration_secs: 60

  internal_logs_to_disk:
    type: file
    inputs:
      - internal_logs
    compression: none
    path: 'C:\Program Files\vector\data\vector-%Y-%m-%d.log'
    encoding:
      codec: json

api:
  enabled: true
  address: "0.0.0.0:8686"

```

WinLogBeat config

```
winlogbeat.registry_file: C:/ProgramData/winlogbeat/.winlogbeat.yml
winlogbeat.event_logs:
  - name: Application
    ignore_older: 24h

  - name: System
    ignore_older: 24h

  - name: Security
    ignore_older: 24h
    event_id: -5156, -5061

  - name: Microsoft-Windows-CertificateServicesClient-Lifecycle-System/Operational
    ignore_older: 24h

  - name: Microsoft-Windows-PowerShell/Operational
    ignore_older: 24h

  - name: Microsoft-Windows-PowerShell/Admin
    ignore_older: 24h

  - name: PowerShellCore/Operational
    ignore_older: 24h

output.logstash:
  hosts: ["localhost:5044"]

logging.level: warning
logging.to_files: true
logging.files:
  path: C:\ProgramData\winlogbeat\Logs
  name: winlogbeat
  keepfiles: 7
  permissions: 0640

```

When running 1 CPU the vector produces logs basically the same as above. It goes away with 2CPUs assigned to the server.

It's also worth noting that the `httplocal` service doesn't seem to have the same problems. It works fine with 1 or 2 CPUs. Although traffic via the httplocal service on this server is very low.

**Comment by jhbigler** [comment]
> @jhbigler Could you please try to reproduce it on the latest Vector (build it from scratch or just wait for the 0.28)? I cannot reproduce the crash on your example with the latest Vector on master on Mac M1 and Fedora 37 - on both machines the example works fine.

Haven't gotten around to building it from scratch but much like @richarddziennmi my issue goes away when 2 vCPU's are assigned to my VM.

**Comment by joscha-alisch** [comment]
> Could you please try to reproduce it on the latest Vector (build it from scratch or just wait for the 0.28)

I just tried with the latest (0.28) and this issue still occurs for us. 

I can also add that we also run vector with 1 cpu per instance.

**Comment by christophemorio** [comment]
I confirm, I still have the issue with docker image 0.28.1-debian .

**Comment by zamazan4ik** [comment]
I was able to reproduce this issue locally. As far as I understand, the issue is related somehow to the following two lines:
- https://github.com/vectordotdev/vector/blob/master/src/sources/util/net/tcp/request_limiter.rs#L18
- https://github.com/vectordotdev/vector/blob/master/src/sources/util/net/tcp/request_limiter.rs#L35

I guess it's somehow related to the possible race condition under resource starvation, which is triggered by limiting CPU quota.

**Comment by zamazan4ik** [comment]
I've created a PR with possible fix: https://github.com/vectordotdev/vector/pull/16858

Please anyone, anyone is affected by this issue - test this branch in your env. You will need to build Vector from this PR and run it in your env.

Thanks in advance.

According to my local tests - the issue should be fixed.
