### ISSUE TITLE
Elasticsearch sink defaults not working

### ISSUE THREAD

**Issue by gsalisbury** [vectordotdev/vector#16719]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

After upgrading from 0.27.0 to 0.28.1 vector panics on start with:

```Mar 08 09:12:33 logstash01.apnic.net vector[6430]: thread 'main' panicked at 'index should not be undefined', src/sinks/elasticsearch/config.rs:240:24```

If I add `bulk.index = "vector-%Y.%m.%d"` to the elasticsearch sink config vector starts.

### Configuration

```text
type = "elasticsearch"
inputs = [
  "http_parser",
]
buffer.max_events = 5000
buffer.type = "memory"
endpoints = [
  "http://elasticsearch:9200",
]
request.concurrency = "adaptive"
```

### Version

0.28.1

### Debug Output

```text
# RUST_BACKTRACE=full vector -vvv --config-dir /etc/vector-test
2023-03-07T23:55:16.022489Z  INFO vector::app: Internal log rate limit configured. internal_log_rate_secs=10
2023-03-07T23:55:16.023207Z  INFO vector::app: Log level is enabled. level="vector=trace,codec=trace,vrl=trace,file_source=trace,tower_limit=trace,rdkafka=trace,buffers=trace,lapin=trace,kube=trace"
2023-03-07T23:55:16.023402Z  INFO vector::app: Loading configs. paths=["/etc/vector-test"]
2023-03-07T23:55:16.028436Z DEBUG vector::config::loading: No secret placeholder found, skipping secret resolution.
2023-03-07T23:55:16.050499Z DEBUG vector::topology::builder: Building new source. component=http
2023-03-07T23:55:16.057143Z DEBUG vector::topology::builder: Building new transform. component=http_parser
2023-03-07T23:55:16.063710Z DEBUG vector::topology::builder: Building new transform. component=journald_parser
2023-03-07T23:55:16.069480Z DEBUG vector::topology::builder: Building new sink. component=elasticsearch
thread 'main' panicked at 'index should not be undefined', src/sinks/elasticsearch/config.rs:240:24
stack backtrace:
   0:     0x557a5194f12e - std::backtrace_rs::backtrace::libunwind::trace::h1d00f3fcf4cb5ac4
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x557a5194f12e - std::backtrace_rs::backtrace::trace_unsynchronized::h920a6ff332484ee2
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x557a5194f12e - std::sys_common::backtrace::_print_fmt::hd7323920c925af6d
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x557a5194f12e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3155a8c966b4beb5
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x557a50fd1fee - core::fmt::write::h062c617411b691df
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/fmt/mod.rs:1209:17
   5:     0x557a5191ab84 - std::io::Write::write_fmt::hb61fdf1275c61e1c
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/io/mod.rs:1682:15
   6:     0x557a5195047f - std::sys_common::backtrace::_print::hd1b4d9664ab500e0
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x557a5195047f - std::sys_common::backtrace::print::hca896ae22beb06cb
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x557a5194ff7d - std::panicking::default_hook::{{closure}}::h0b5eeed5cf36ab5f
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:267:22
   9:     0x557a51951236 - std::panicking::default_hook::h8932b573145a321b
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:286:9
  10:     0x557a51951236 - std::panicking::rust_panic_with_hook::h4b1447a24e3e94f8
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:688:13
  11:     0x557a51950bc2 - std::panicking::begin_panic_handler::{{closure}}::h8701da9995a3820c
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:579:13
  12:     0x557a51950b2c - std::sys_common::backtrace::__rust_end_short_backtrace::hb696c5ed02a01598
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x557a51950b01 - rust_begin_unwind
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
  14:     0x557a509bed82 - core::panicking::panic_fmt::h8aa706a976963c88
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
  15:     0x557a50fd6960 - core::panicking::panic_display::h145080b539a57164
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:139:5
  16:     0x557a50fd690b - core::panicking::panic_str::hb7f52c873200464f
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:123:5
  17:     0x557a509beef6 - core::option::expect_failed::hf416ac71eef81151
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/option.rs:1879:5
  18:     0x557a536009be - vector::sinks::elasticsearch::common::ElasticsearchCommon::parse_config::{{closure}}::heb0cb671caab5e7f
  19:     0x557a535f6d9e - <vector::sinks::elasticsearch::config::ElasticsearchConfig as vector::config::sink::SinkConfig>::build::{{closure}}::h8cad998b57e5054d
  20:     0x557a535f6252 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h3a077b8a6580a90b
  21:     0x557a5323608f - vector::topology::builder::build_pieces::{{closure}}::h5622d85800619662
  22:     0x557a53202301 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h26dbe0590d865b63
  23:     0x557a531f0e84 - vector::app::Application::prepare_from_opts::{{closure}}::he69c81485d48c23e
  24:     0x557a531e5916 - vector::app::Application::prepare_from_opts::h8af471d5028d7561
  25:     0x557a50a9d09c - vector::main::hc0d3c98244aa10b9
  26:     0x557a50a9b283 - std::sys_common::backtrace::__rust_begin_short_backtrace::h162e7a888393dbc5
  27:     0x557a50aa0b39 - main
  28:     0x7f39dc203555 - __libc_start_main
  29:     0x557a50a9b18a - <unknown>
  30:                0x0 - <unknown>
```

### References

May have been introduced by https://github.com/vectordotdev/vector/pull/16223

**Comment by zamazan4ik** [comment]
@gsalisbury could you please test the linked PR? Now it should work as expected without a crash.

**Comment by neuronull** [comment]
> May have been introduced by https://github.com/vectordotdev/vector/pull/16223

Confirmed.

Added some feedback to the PR from @zamazan4ik
