### ISSUE TITLE
Vector agent unexpected error with tokio-runtime-worker

### ISSUE THREAD

**Issue by pavellysianok** [vectordotdev/vector#17060]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I'm trying to use the sink out for sending the scrapped logs to Azure Eventhub in Default topic but I got the unexpected error like this:
```sh
ERROR source{component_kind="source" component_name=spark_error_logs component_type=file}:file_server: file_source::file_server: Output channel closed. error=send failed because receiver is gone
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { kind: Disconnected }', src/sources/file.rs:393:20
```
The service status output like this:
```sh
Apr 05 14:58:36 ****************-5 vector[1661]: Apr 05 14:58:36.126  INFO vector::topology: Starting sink. name="out"

Apr 05 14:58:36 ****************-5 vector[1661]: Apr 05 14:58:36.126  INFO vector: Vector has started. debug="false" version="0.13.1" arch="x86_64" build_id="c5e4732 2021-07-27"

Apr 05 14:58:36 ****************-5 vector[1661]: Apr 05 14:58:36.126  INFO vector::internal_events::api: API server running. address=127.0.0.1:8686 playground=http://127.0.0.1:8686/playground

Apr 05 14:58:36 ****************-5 vector[1661]: Apr 05 14:58:36.126  INFO source{component_kind="source" component_name=spark_error_logs component_type=file}: vector::sources::file: Starting file server. include=["/dbfs/cluster-logs/**/driver/stderr"] exclude=[]

Apr 05 14:58:36 ****************-5 vector[1661]: Apr 05 14:58:36.127  INFO source{component_kind="source" component_name=spark_error_logs component_type=file}:file_server: file_source::checkpointer: Loaded checkpoint data.

Apr 05 14:58:36 ****************-5 vector[1661]: Apr 05 14:58:36.455  WARN source{component_kind="source" component_name=spark_error_logs component_type=file}:file_server: vector::internal_events::file::source: Currently ignoring file too small to fingerprint. path=/dbfs/cluster-logs/******/driver/stderr

Apr 05 14:58:36 ****************-5 vector[1661]: Apr 05 14:58:36.456  WARN source{component_kind="source" component_name=spark_error_logs component_type=file}:file_server: vector::internal_events::file::source: Currently ignoring file too small to fingerprint. path=/dbfs/cluster-logs/******/driver/stderr

Apr 05 15:04:36 ****************-5 vector[1661]: Apr 05 15:04:36.704 ERROR rdkafka::client: librdkafka: Global error: OperationTimedOut (Local: Timed out): sasl_ssl://******.servicebus.windows.net:9093/0: 1 request(s) timed out: disconnect (after 360258ms in state UP)

Apr 05 15:04:36 ****************-5 vector[1661]: Apr 05 15:04:36.705 ERROR rdkafka::client: librdkafka: Global error: AllBrokersDown (Local: All broker connections are down): 1/1 brokers are down

Apr 05 15:13:28 ****************-5 vector[1661]: Apr 05 15:13:28.835 ERROR rdkafka::client: librdkafka: Global error: AllBrokersDown (Local: All broker connections are down): 1/1 brokers are down
```

### Configuration

```text
[sinks.out]
    type = "kafka"
    inputs = ["transform_add_fields"]
    topic = "example_topic"
    compression = "none"
    healthcheck = false
    encoding.codec = "json"

    # initial brokers for reading cluster metadata
    # this value is filled in from script.sh
    bootstrap_servers = ""


    sasl.enabled = true
    sasl.mechanism = "PLAIN"
    sasl.username = "$$ConnectionString"
    sasl.password = "$PASSWORD"
    librdkafka_options."sasl.mechanism" = "PLAIN"
    librdkafka_options."security.protocol" = "sasl_ssl"
    librdkafka_options."sasl.username"  = "$$ConnectionString"
    librdkafka_options."sasl.password"  = "$PASSWORD"
    tls.enabled = true
    tls.verify_certificate = false
    group.id="$$Default"

[api]
    enabled = true
```

### Version

0.13.1

### Debug Output

```text
Apr 05 15:39:26.542  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info"
Apr 05 15:39:26.542  INFO vector::sources::host_metrics: PROCFS_ROOT is unset. Using default '/proc' for procfs root.
Apr 05 15:39:26.542  INFO vector::sources::host_metrics: SYSFS_ROOT is unset. Using default '/sys' for sysfs root.
Apr 05 15:39:26.542  INFO vector::app: Loading configs. path=[("/etc/vector/vector.toml", None)]
Apr 05 15:39:26.553  INFO vector::topology: Running healthchecks.
Apr 05 15:39:26.553  INFO vector::topology: Starting source. name="spark_error_logs"
Apr 05 15:39:26.554  INFO vector::topology::builder: Healthcheck: Disabled.
Apr 05 15:39:26.554  INFO vector::topology: Starting transform. name="transform_add_fields"
Apr 05 15:39:26.554  INFO vector::topology: Starting sink. name="out"
Apr 05 15:39:26.554  INFO source{component_kind="source" component_name=spark_error_logs component_type=file}: vector::sources::file: Starting file server. include=["/dbfs/cluster-logs/**/driver/stderr"] exclude=[]
Apr 05 15:39:26.554  INFO vector: Vector has started. version="0.13.1" git_version="v0.13.1" released="Thu, 29 Apr 2021 14:20:13 +0000" arch="x86_64"
Apr 05 15:39:26.555  INFO vector::internal_events::api: API server running. address=127.0.0.1:8686 playground=http://127.0.0.1:8686/playground
Apr 05 15:39:26.555  INFO source{component_kind="source" component_name=spark_error_logs component_type=file}:file_server: file_source::checkpointer: Loaded checkpoint data.
thread 'main' panicked at 'error binding to 127.0.0.1:8686: error creating server listener: Address already in use (os error 98)', /cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.3.1/src/server.rs:283:27
stack backtrace:
   0:     0x55bbb1dbdeb3 - std::backtrace_rs::backtrace::libunwind::trace::h5e9d00f0cdf4f57e
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55bbb1dbdeb3 - std::backtrace_rs::backtrace::trace_unsynchronized::hd5302bd66215dab9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55bbb1dbdeb3 - std::sys_common::backtrace::_print_fmt::ha0237cd11a34e2bf
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55bbb1dbdeb3 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h171d4c10df1a98ee
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55bbb15e8e4c - core::fmt::write::h89e4288724daa3fa
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/mod.rs:1096:17
   5:     0x55bbb1dbd761 - std::io::Write::write_fmt::h6d40f996e84584d9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/io/mod.rs:1568:15
   6:     0x55bbb1dbd105 - std::sys_common::backtrace::_print::h0c0b93221682afc8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55bbb1dbd105 - std::sys_common::backtrace::print::h57a9f95204c2fdd6
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55bbb1dbd105 - std::panicking::default_hook::{{closure}}::h4245258b50e37e69
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:208:50
   9:     0x55bbb1dbc76a - std::panicking::default_hook::h7b00dcc1d0944747
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:225:9
  10:     0x55bbb1dbc76a - std::panicking::rust_panic_with_hook::h71e6a073d87de1f5
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:591:17
  11:     0x55bbb1ddae58 - std::panicking::begin_panic_handler::{{closure}}::hd549436f6bb6dbb8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
  12:     0x55bbb1ddadcc - std::sys_common::backtrace::__rust_end_short_backtrace::h4e5f4b72b04174c3
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55bbb1ddad7d - rust_begin_unwind
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
  14:     0x55bbb1ddad40 - std::panicking::begin_panic_fmt::h818c3c917eaeb432
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:435:5
  15:     0x55bbb313c1c3 - warp::server::Server<F>::bind_with_graceful_shutdown::{{closure}}::ha663f4c09b3d7d04
  16:     0x55bbb31397be - vector::api::server::Server::start::h2c6f9746d08be324
  17:     0x55bbb342b538 - vector::app::Application::run::{{closure}}::h1d72ec60f7990759
  18:     0x55bbb143cbe6 - vector::main::h237633b12f12c884
  19:     0x55bbb143c6b3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h94fd677584b8caa8
  20:     0x55bbb143e357 - main
  21:     0x7f5454aad083 - __libc_start_main
  22:     0x55bbb143c5ba - <unknown>
  23:                0x0 - <unknown>
Apr 05 15:39:26.884  WARN source{component_kind="source" component_name=spark_error_logs component_type=file}:file_server: vector::internal_events::file::source: Currently ignoring file too small to fingerprint. path=/dbfs/cluster-logs/*******/driver/stderr


Apr 05 15:39:26.885  WARN source{component_kind="source" component_name=spark_error_logs component_type=file}:file_server: vector::internal_events::file::source: Currently ignoring file too small to fingerprint. path=/dbfs/cluster-logs/***********/driver/stderr
Apr 05 15:39:27.204 ERROR source{component_kind="source" component_name=spark_error_logs component_type=file}:file_server: file_source::file_server: Output channel closed. error=send failed because receiver is gone
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { kind: Disconnected }', src/sources/file.rs:347:20
stack backtrace:
   0:     0x55bbb1dbdeb3 - std::backtrace_rs::backtrace::libunwind::trace::h5e9d00f0cdf4f57e
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55bbb1dbdeb3 - std::backtrace_rs::backtrace::trace_unsynchronized::hd5302bd66215dab9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55bbb1dbdeb3 - std::sys_common::backtrace::_print_fmt::ha0237cd11a34e2bf
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55bbb1dbdeb3 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h171d4c10df1a98ee
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55bbb15e8e4c - core::fmt::write::h89e4288724daa3fa
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/mod.rs:1096:17
   5:     0x55bbb1dbd761 - std::io::Write::write_fmt::h6d40f996e84584d9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/io/mod.rs:1568:15
   6:     0x55bbb1dbd105 - std::sys_common::backtrace::_print::h0c0b93221682afc8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55bbb1dbd105 - std::sys_common::backtrace::print::h57a9f95204c2fdd6
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55bbb1dbd105 - std::panicking::default_hook::{{closure}}::h4245258b50e37e69
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:208:50
   9:     0x55bbb1dbc76a - std::panicking::default_hook::h7b00dcc1d0944747
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:225:9
  10:     0x55bbb1dbc76a - std::panicking::rust_panic_with_hook::h71e6a073d87de1f5
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:591:17
  11:     0x55bbb1ddae58 - std::panicking::begin_panic_handler::{{closure}}::hd549436f6bb6dbb8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
  12:     0x55bbb1ddadcc - std::sys_common::backtrace::__rust_end_short_backtrace::h4e5f4b72b04174c3
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55bbb1ddad7d - rust_begin_unwind
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
  14:     0x55bbb15e6610 - core::panicking::panic_fmt::hcd56f7f635f62c74
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
  15:     0x55bbb15ed472 - core::option::expect_none_failed::hf37eebedadde29e6
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
  16:     0x55bbb22039f2 - tokio::runtime::task::raw::poll::h352f0089bc871677
  17:     0x55bbb1e19957 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha60a0cfd5541021e
  18:     0x55bbb1e19578 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h459ca2a615617dad
  19:     0x55bbb1df33ba - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h61144a2be4ee36d8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
  20:     0x55bbb1df33ba - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcf5d395fdd120c17
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
  21:     0x55bbb1df33ba - std::sys::unix::thread::Thread::new::thread_start::hb5e40d3d934ebb7a
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
  22:     0x7f5454ffd609 - start_thread
  23:     0x7f5454ba8133 - clone
  24:                0x0 - <unknown>
root@*************:/databricks/driver# RUST_BACKTRACE=full vector --config=/etc/vector/vector.toml > 4.txt
thread 'main' panicked at 'error binding to 127.0.0.1:8686: error creating server listener: Address already in use (os error 98)', /cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.3.1/src/server.rs:283:27
stack backtrace:
   0:     0x560739a1aeb3 - std::backtrace_rs::backtrace::libunwind::trace::h5e9d00f0cdf4f57e
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x560739a1aeb3 - std::backtrace_rs::backtrace::trace_unsynchronized::hd5302bd66215dab9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x560739a1aeb3 - std::sys_common::backtrace::_print_fmt::ha0237cd11a34e2bf
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x560739a1aeb3 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h171d4c10df1a98ee
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x560739245e4c - core::fmt::write::h89e4288724daa3fa
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/mod.rs:1096:17
   5:     0x560739a1a761 - std::io::Write::write_fmt::h6d40f996e84584d9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/io/mod.rs:1568:15
   6:     0x560739a1a105 - std::sys_common::backtrace::_print::h0c0b93221682afc8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x560739a1a105 - std::sys_common::backtrace::print::h57a9f95204c2fdd6
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x560739a1a105 - std::panicking::default_hook::{{closure}}::h4245258b50e37e69
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:208:50
   9:     0x560739a1976a - std::panicking::default_hook::h7b00dcc1d0944747
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:225:9
  10:     0x560739a1976a - std::panicking::rust_panic_with_hook::h71e6a073d87de1f5
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:591:17
  11:     0x560739a37e58 - std::panicking::begin_panic_handler::{{closure}}::hd549436f6bb6dbb8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
  12:     0x560739a37dcc - std::sys_common::backtrace::__rust_end_short_backtrace::h4e5f4b72b04174c3
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x560739a37d7d - rust_begin_unwind
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
  14:     0x560739a37d40 - std::panicking::begin_panic_fmt::h818c3c917eaeb432
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:435:5
  15:     0x56073ad991c3 - warp::server::Server<F>::bind_with_graceful_shutdown::{{closure}}::ha663f4c09b3d7d04
  16:     0x56073ad967be - vector::api::server::Server::start::h2c6f9746d08be324
  17:     0x56073b088538 - vector::app::Application::run::{{closure}}::h1d72ec60f7990759
  18:     0x560739099be6 - vector::main::h237633b12f12c884
  19:     0x5607390996b3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h94fd677584b8caa8
  20:     0x56073909b357 - main
  21:     0x7f167bc3b083 - __libc_start_main
  22:     0x5607390995ba - <unknown>
  23:                0x0 - <unknown>
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { kind: Disconnected }', src/sources/file.rs:347:20
stack backtrace:
   0:     0x560739a1aeb3 - std::backtrace_rs::backtrace::libunwind::trace::h5e9d00f0cdf4f57e
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x560739a1aeb3 - std::backtrace_rs::backtrace::trace_unsynchronized::hd5302bd66215dab9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x560739a1aeb3 - std::sys_common::backtrace::_print_fmt::ha0237cd11a34e2bf
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x560739a1aeb3 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h171d4c10df1a98ee
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x560739245e4c - core::fmt::write::h89e4288724daa3fa
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/mod.rs:1096:17
   5:     0x560739a1a761 - std::io::Write::write_fmt::h6d40f996e84584d9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/io/mod.rs:1568:15
   6:     0x560739a1a105 - std::sys_common::backtrace::_print::h0c0b93221682afc8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x560739a1a105 - std::sys_common::backtrace::print::h57a9f95204c2fdd6
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x560739a1a105 - std::panicking::default_hook::{{closure}}::h4245258b50e37e69
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:208:50
   9:     0x560739a1976a - std::panicking::default_hook::h7b00dcc1d0944747
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:225:9
  10:     0x560739a1976a - std::panicking::rust_panic_with_hook::h71e6a073d87de1f5
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:591:17
  11:     0x560739a37e58 - std::panicking::begin_panic_handler::{{closure}}::hd549436f6bb6dbb8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
  12:     0x560739a37dcc - std::sys_common::backtrace::__rust_end_short_backtrace::h4e5f4b72b04174c3
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x560739a37d7d - rust_begin_unwind
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
  14:     0x560739243610 - core::panicking::panic_fmt::hcd56f7f635f62c74
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
  15:     0x56073924a472 - core::option::expect_none_failed::hf37eebedadde29e6
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
  16:     0x560739e609f2 - tokio::runtime::task::raw::poll::h352f0089bc871677
  17:     0x560739a76957 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha60a0cfd5541021e
  18:     0x560739a76578 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h459ca2a615617dad
  19:     0x560739a503ba - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h61144a2be4ee36d8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
  20:     0x560739a503ba - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcf5d395fdd120c17
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
  21:     0x560739a503ba - std::sys::unix::thread::Thread::new::thread_start::hb5e40d3d934ebb7a
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
  22:     0x7f167c18b609 - start_thread
  23:     0x7f167bd36133 - clone
  24:                0x0 - <unknown>
```

### Description
I have the same configuration in another environment ( separate Databricks cluster) and it works correctly. The existing connection string is checked and valid. The firewall is turned off, there are no connectivity issues.

**Comment by neuronull** [comment]
👋  hello, `v0.13.1` is quite old (about 2 years). Is there a specific reason you are using such an old version, and any chance of being able to see if this reproduces on a newer version such as the latest, `v0.28.1` ?

**Comment by pavellysianok** [comment]
I tried to install the latest Vector version but I have a problem with vector.toml with the "group_id" parameter which marked Vector as unexpected. This is very strange because according to the documentation, this is required but can't be parsed.

**Comment by zamazan4ik** [comment]
Well, you should update your Vector instance to the latest version. With the latest version, there is a huge chance to get your problem fixed automatically.

Getting any kind of support for the so old version would be... almost impossible :)

**Comment by neuronull** [comment]
If you look at the latest documentation, you will see that `group_id` is not at the root level of that sink's settings.
It moved into `librdkafka_options` some time ago.

https://vector.dev/docs/reference/configuration/sinks/kafka/#librdkafka_options
