### ISSUE TITLE
Kafka sink with buffer type disk is not starting

### ISSUE THREAD

**Issue by gl1ridae** [vectordotdev/vector#18503]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When I'm trying to create kafka sink with buffer type **disk**, vector service not starting properly.

### Configuration

```text
sources:
  src_http_server_443:
    type: http_server
    address: 0.0.0.0:443
    strict_path: false
    auth:
      strategy: basic
      username: vector
      password: vector
    tls:
      enabled: true
      key_file: /etc/vector/ssl/key.pem
      crt_file: /etc/vector/ssl/certificate.pem
transforms:
  tfm_route_from_http_server_443:
    type: route
    inputs:
    - src_http_server_443
    route:
      my_path:
        type: vrl
        source: '%http_server.path == "/my-path"'
sinks:
  snk_http_server:
    type: kafka
    inputs:
    - tfm_route_from_http_server_443.my_path
    bootstrap_servers: broker1:9092,broker2:9092,broker3:9092
    topic: my-path
    acknowledgements:
      enabled: true
    buffer:
      type: disk
      when_full: block
      max_size: 268435488
    encoding:
      codec: raw_message
```

### Version

0.32.1

### Debug Output

```text
thread 'vector-worker' panicked at 'payload should never be zero length', src/sinks/kafka/request_builder.rs:56:55
stack backtrace:
   0:     0x55ad6acdb2b4 - std::backtrace_rs::backtrace::libunwind::trace::h782cc21a5acaf6cb
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55ad6acdb2b4 - std::backtrace_rs::backtrace::trace_unsynchronized::hc579eb24ab204515
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55ad6acdb2b4 - std::sys_common::backtrace::_print_fmt::h7223525cfdbacda2
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55ad6acdb2b4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbd7d55b7108d2ab8
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55ad6a36213f - core::fmt::rt::Argument::fmt::hb4f4a02b9bd9dd49
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/fmt/rt.rs:138:9
   5:     0x55ad6a36213f - core::fmt::write::h6d54cd7c9e155ec5
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/fmt/mod.rs:1094:21
   6:     0x55ad6aca5b40 - std::io::Write::write_fmt::h6a453a71c692f63b
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/io/mod.rs:1713:15
   7:     0x55ad6acdfd6f - std::sys_common::backtrace::_print::h1cbaa8b42678f928
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55ad6acdfd6f - std::sys_common::backtrace::print::h4ddf81241a51b337
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55ad6acdf5a7 - std::panicking::default_hook::{{closure}}::hff91f1f484ade5cd
  10:     0x55ad6ace0523 - std::panicking::default_hook::h21f14afd59f7aef9
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:288:9
  11:     0x55ad6ace0523 - std::panicking::rust_panic_with_hook::h45f66047b14c555c
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:705:13
  12:     0x55ad6ace0002 - std::panicking::begin_panic_handler::{{closure}}::h49d1a88ef0908eb4
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:597:13
  13:     0x55ad6acdff66 - std::sys_common::backtrace::__rust_end_short_backtrace::hccebf9e57f8cc425
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:151:18
  14:     0x55ad6acdff51 - rust_begin_unwind
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
  15:     0x55ad69ca9fb2 - core::panicking::panic_fmt::h54ec9d0e3180a83d
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
  16:     0x55ad69caa4f2 - core::panicking::panic_display::h0e30bc17bca455bf
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:150:5
  17:     0x55ad69caa4f2 - core::panicking::panic_str::h3f2c4f87e890c4a7
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:134:5
  18:     0x55ad69caa4f2 - core::option::expect_failed::h03fbde71aa9ac6b4
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/option.rs:1932:5
  19:     0x55ad6b7a9d5d - vector_core::stream::driver::Driver<St,Svc>::run::{{closure}}::hc91e8c2f0f439631
  20:     0x55ad6b7a2a21 - <vector::sinks::kafka::sink::KafkaSink as vector_core::sink::StreamSink<vector_core::event::Event>>::run::{{closure}}::h1072ffe9dc3c13ec
  21:     0x55ad6b7a23dc - <vector_core::sink::EventStream<T> as vector_core::sink::StreamSink<vector_core::event::array::EventArray>>::run::{{closure}}::hcbf28061932f9cee
  22:     0x55ad6d0b9af1 - vector::topology::builder::Builder::build_sinks::{{closure}}::{{closure}}::hddfb30003d359257
  23:     0x55ad6d0841fe - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::hd65906931d652f65
  24:     0x55ad6d0836f1 - tokio::runtime::task::raw::poll::ha58eb3b2d0de7ed1
  25:     0x55ad6ad2537b - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h56829edec9390b23
  26:     0x55ad6ad2ac64 - tokio::runtime::task::raw::poll::h59672495db66a235
  27:     0x55ad6ad0f79c - std::sys_common::backtrace::__rust_begin_short_backtrace::h6aab76a8c7f848ad
  28:     0x55ad6ad0f4a0 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hd61caea1acb24c0c
  29:     0x55ad6ace29f5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he3e5dbdfabe0b668
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/alloc/src/boxed.rs:1985:9
  30:     0x55ad6ace29f5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h246f7c7964633611
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/alloc/src/boxed.rs:1985:9
  31:     0x55ad6ace29f5 - std::sys::unix::thread::Thread::new::thread_start::hadf9e3501ff0df23
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys/unix/thread.rs:108:17
  32:     0x7fd3bc85b609 - start_thread
  33:     0x7fd3bc629163 - clone
  34:                0x0 - <unknown>
 ERROR sink{component_kind="sink" component_id=snk_http_server component_type=kafka component_name=snk_http_server}: vector::topology: An error occurred that Vector couldn't handle: the task panicked and was abort>
 INFO vector: Vector has stopped.
 INFO vector::topology::running: Shutting down... Waiting on running components. remaining_components="..." time_remaining="59 seconds left"
systemd[1]: vector.service: Succeeded.
```

### Additional Context

When buffer type set to memory - it's working as expected.

**Comment by jszwedko** [comment]
Thanks for filing this @gl1ridae !

I'm wondering if it is related to https://github.com/vectordotdev/vector/issues/11931

As a side note, we'd typically not recommend using a disk buffer with a Kafka sink as Kafka is already designed to be a durable store.

**Comment by jszwedko** [comment]
Yeah, let's roll this into https://github.com/vectordotdev/vector/issues/11931. Thanks @gl1ridae !
