### ISSUE TITLE
gcp_cloud_storage sink: thread 'vector-worker' panicked at 'Reader encountered unrecoverable error: Io' - Vector Aggregator

### ISSUE THREAD

**Issue by Abhinav04** [vectordotdev/vector#19045]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Vector aggregator panicks and gets restarted for gcp_cloud_storage sink intermittently

Vector Version
`vector 0.26.0`

Log
```
2023-11-03T08:16:57.126512Z  INFO vector::topology::builder: Healthcheck passed.
2023-11-03T08:16:57.144758Z  INFO vector::topology::builder: Healthcheck passed.
2023-11-03T08:16:57.160504Z  INFO vector::topology::builder: Healthcheck passed.
2023-11-03T13:47:06.246087Z ERROR sink{component_kind="sink" component_id=cloud_storage component_type=gcp_cloud_storage component_name=cloud_storage}:sink{buffer_type="disk"}: vector_buffers::internal_events: Events dropped. count=18446744073709487194 intentional=false reason=corrupted_events stage=0
thread 'vector-worker' panicked at 'Reader encountered unrecoverable error: Io { source: Os { code: 2, kind: NotFound, message: "No such file or directory" } }', /project/lib/vector-buffers/src/topology/channel/receiver.rs:59:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-11-03T13:47:08.979414Z ERROR sink{component_kind="sink" component_id=cloud_storage component_type=gcp_cloud_storage component_name=cloud_storage}: vector::topology: An error occurred that Vector couldn't handle: the task panicked and was aborted.
2023-11-03T13:47:08.979575Z  INFO vector: Vector has stopped.
```

Additional Context

Flow:

```Kubernetes Pods --> Vector Agent --> Vector Aggregator --> Google Cloud Storage Bucket```

Vector aggregator works fine throughout but fails intermittently after a few hours and gets restarted with the above error.
Good amount of CPU and Memory is available on nodes running vector aggregator pods.

### Version

vector-0.26.0

**Comment by StephenWakely** [comment]
The error is likely occurring because the buffer file that Vector is using ceases to exist. How is `/vector-data-dir` mounted to the pod?

**Comment by Abhinav04** [comment]
> The error is likely occurring because the buffer file that Vector is using ceases to exist. How is `/vector-data-dir` mounted to the pod?

@StephenWakely /vector-data-dir is mounted in the form of a persistent disk ([Persistent Volume](https://kubernetes.io/docs/concepts/storage/persistent-volumes/)). Vector aggregator is deployed as a stateful set backed by persistent disks.

**Comment by StephenWakely** [comment]
Can you think of any reason why Vector may lose access to that disk? When Vector is restarted do you have any data loss?

**Comment by StephenWakely** [comment]
The count is a bit suspicious. That's a lot of events to drop!

Are you able to confirm if this error occurs on the latest version of Vector (0.33.1)? 0.26 is quite old.

**Comment by Abhinav04** [comment]
@StephenWakely We have multiple other clusters which are running Vector 0.32.0 and similar error is being seen on most of the clusters. 

Here's a log snippet from one of the clusters:
```
2023-11-04T15:35:24.377344Z  INFO vector::app: Log level is enabled. level="INFO"
2023-11-04T15:35:24.377372Z  WARN vector::app: DEPRECATED The openssl legacy provider provides algorithms and key sizes no longer recommended for use.
2023-11-04T15:35:24.377676Z  INFO vector::app: Loaded openssl legacy provider.
2023-11-04T15:35:24.378435Z  INFO vector::config::watcher: Creating configuration file watcher.
2023-11-04T15:35:24.378790Z  INFO vector::config::watcher: Watching configuration files.
2023-11-04T15:35:24.378873Z  INFO vector::app: Loading configs. paths=["/etc/vector"]
2023-11-04T15:35:24.905010Z  INFO vector::topology::running: Running healthchecks.
2023-11-04T15:35:24.905209Z  INFO vector: Vector has started. debug="false" version="0.32.0" arch="x86_64" revision="1b403e1 2023-08-15 14:56:36.089460954"
2023-11-04T15:35:24.905270Z  INFO source{component_kind="source" component_id=agent component_type=vector component_name=agent}: vector::sources::util::grpc: Building gRPC server. address=0.0.0.0:6000
2023-11-04T15:35:24.907948Z  INFO vector::internal_events::api: API server running. address=0.0.0.0:8686 playground=off
2023-11-04T15:35:26.282392Z  INFO vector::topology::builder: Healthcheck passed.
2023-11-04T15:35:26.311784Z  INFO vector::topology::builder: Healthcheck passed.
2023-11-04T15:35:26.409646Z  INFO vector::topology::builder: Healthcheck passed.
2023-11-07T06:45:57.670473Z  WARN sink{component_kind="sink" component_id=cloud_storage component_type=gcp_cloud_storage component_name=cloud_storage}:request{request_id=122254}: vector::sinks::util::retries: Retrying after response. reason=500 Internal Server Error internal_log_rate_limit=true
thread 'vector-worker' panicked at 'Reader encountered unrecoverable error: Io { source: Os { code: 2, kind: NotFound, message: "No such file or directory" } }', /project/lib/vector-buffers/src/topology/channel/receiver.rs:59:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-11-07T09:57:20.565298Z ERROR sink{component_kind="sink" component_id=cloud_storage component_type=gcp_cloud_storage component_name=cloud_storage}:sink{buffer_type="disk"}: vector_buffers::internal_events: Events dropped. count=18446744073709508238 intentional=false reason=corrupted_events stage=0
2023-11-07T09:57:21.474346Z ERROR sink{component_kind="sink" component_id=cloud_storage component_type=gcp_cloud_storage component_name=cloud_storage}: vector::topology: An error occurred that Vector couldn't handle: the task panicked and was aborted.
2023-11-07T09:57:21.474457Z  INFO vector: Vector has stopped.
```

**Comment by yanjun-li** [comment]
I also encountered this problem when using s3 sink. Any suggestions?

**Comment by StephenWakely** [comment]
> I also encountered this problem when using s3 sink. Any suggestions?

The issue is not specific to any particular sink. The issue seems to be when the Vector loses access the file that it is storing the buffer on. Can you provide more details about the volume the `data_dir` is pointing to?

**Comment by yanjun-li** [comment]
@StephenWakely  The data_dir is pointing to a persistent volume in EKS.  


Here is the log:
```
2023-11-21T07:33:02.047747Z  INFO vector::topology::builder: Healthcheck passed.
thread 'vector-worker' panicked at 'Reader encountered unrecoverable error: Io { source: Os { code: 2, kind: NotFound, message: "No such file or directory" } }', /project/lib/vector-buffers/src/topology/channel/receiver.rs:59:33
stack backtrace:
   0:     0xaaaad70594a0 - std::backtrace_rs::backtrace::libunwind::trace::hc366d13e3075cfeb
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0xaaaad70594a0 - std::backtrace_rs::backtrace::trace_unsynchronized::hb9a35e1f782586fe
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0xaaaad70594a0 - std::sys_common::backtrace::_print_fmt::hae0d6c377f414e8d
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:65:5
   3:     0xaaaad70594a0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0f8916ea7cac138e
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0xaaaad6828860 - core::fmt::rt::Argument::fmt::hf491ec0da00c9b40
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/fmt/rt.rs:138:9
   5:     0xaaaad6828860 - core::fmt::write::h075f235dea7f2ae2
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/fmt/mod.rs:1094:21
   6:     0xaaaad702107c - std::io::Write::write_fmt::hed461f96db027bb0
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/io/mod.rs:1714:15
   7:     0xaaaad705c104 - std::sys_common::backtrace::_print::h9f6cc87d40ba87f7
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:47:5
   8:     0xaaaad705c104 - std::sys_common::backtrace::print::hc36324e2f472d029
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:34:9
   9:     0xaaaad705bd04 - std::panicking::default_hook::{{closure}}::h8d8f8741b904046c
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:269:22
  10:     0xaaaad705cc2c - std::panicking::default_hook::h6fd0090c1af86ae9
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:288:9
  11:     0xaaaad705cc2c - std::panicking::rust_panic_with_hook::h25082e1f49b04873
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:705:13
  12:     0xaaaad705c760 - std::panicking::begin_panic_handler::{{closure}}::hd64c14bd1869359d
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:597:13
  13:     0xaaaad705c6d4 - std::sys_common::backtrace::__rust_end_short_backtrace::h8613664e493d4a0e
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:151:18
  14:     0xaaaad705c6c8 - rust_begin_unwind
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
  15:     0xaaaad626ff10 - core::panicking::panic_fmt::h354dad60a2e185d5
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
  16:     0xaaaad8befef4 - vector_buffers::topology::channel::receiver::ReceiverAdapter<T>::next::{{closure}}::hd01ea73e57558309
  17:     0xaaaad8bef180 - vector_buffers::topology::channel::receiver::BufferReceiver<T>::next::{{closure}}::hb2fd72c713890c51
  18:     0xaaaad8f23ae0 - vector_buffers::topology::channel::receiver::make_recv_future::{{closure}}::h8bde19c02063e358
  19:     0xaaaad8f41bf4 - <vector_buffers::topology::channel::receiver::BufferReceiverStream<T> as futures_core::stream::Stream>::poll_next::hc22bfbb6df1b82e8
  20:     0xaaaad8f412b8 - <vector::utilization::Utilization<S> as futures_core::stream::Stream>::poll_next::h797c2c8c6db0517e
  21:     0xaaaad8f40d18 - <stream_cancel::combinator::TakeUntilIf<S,F> as futures_core::stream::Stream>::poll_next::h4d57577fca8bce3f
  22:     0xaaaad726fc94 - <futures_util::stream::stream::FlatMap<St,U,F> as futures_core::stream::Stream>::poll_next::h317498fdf5ec7754
  23:     0xaaaad758b570 - <vector_core::stream::partitioned_batcher::PartitionedBatcher<St,Prt,KT> as futures_core::stream::Stream>::poll_next::hcaafe2d3da438c2f
  24:     0xaaaad7580a90 - <vector::sinks::s3_common::sink::S3Sink<Svc,RB> as vector_core::sink::StreamSink<vector_core::event::Event>>::run::{{closure}}::h62aa3ccbf71cb5c0
  25:     0xaaaad757e77c - <vector_core::sink::EventStream<T> as vector_core::sink::StreamSink<vector_core::event::array::EventArray>>::run::{{closure}}::h8a41f58bf9c39efa
  26:     0xaaaad8f3ff38 - vector::topology::builder::Builder::build_sinks::{{closure}}::{{closure}}::hb14f5ad14bc172c1
  27:     0xaaaad8f032ec - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::hd774630cd39b8642
  28:     0xaaaad8f02b88 - tokio::runtime::task::raw::poll::hc33b78532c44772c
  29:     0xaaaad70a00b4 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hbfa7fdd8cfe3f82d
  30:     0xaaaad70a5000 - tokio::runtime::task::raw::poll::h585308cd792d3405
  31:     0xaaaad708a6b8 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5c4c394bb284ddb5
  32:     0xaaaad708a3a4 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc419499b44d1e34f
  33:     0xaaaad705f0a8 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd6a6c972c6220bcb
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:1993:9
  34:     0xaaaad705f0a8 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3b759ee01954e7b0
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:1993:9
  35:     0xaaaad705f0a8 - std::sys::unix::thread::Thread::new::thread_start::hd2c1311433b59ac2
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys/unix/thread.rs:108:17
  36:     0xffff88fbee18 - <unknown>
  37:     0xffff89027e9c - <unknown>
  38:                0x0 - <unknown>
2023-11-21T11:50:31.597101Z ERROR sink{component_kind="sink" component_id=request_s3 component_type=aws_s3 component_name=request_s3}: vector::topology: An error occurred that Vector couldn't handle: the task panicked and was aborted.
2023-11-21T11:50:31.597150Z  INFO vector: Vector has stopped.
2023-11-21T11:50:31.599252Z  INFO vector::topology::running: Shutting down... Waiting on running components. remaining_components="report, report_s3, kafka_remap, request, kafka_report, kafka_request" time_remaining="119 seconds left"
2023-11-21T11:50:31.857252Z ERROR sink{component_kind="sink" component_id=request_s3 component_type=aws_s3 component_name=request_s3}:sink{buffer_type="disk"}: vector_buffers::internal_events: Events dropped. count=18446744073709401251 intentional=false reason=corrupted_events stage=0
2023-11-21T11:50:36.598370Z  INFO vector::topology::running: Shutting down... Waiting on running components. remaining_components="report_s3" time_remaining="114 seconds left"
```

**Comment by StephenWakely** [comment]
@yanjun-li @Abhinav04 Is it possible that multiple Vector pods are sharing the same persistent volume?

**Comment by Abhinav04** [comment]
@StephenWakely In our case it is not possible. We have only one pod per node and only one volume gets attached to the node. Hence volumes are not shared amongst pods.

**Comment by yanjun-li** [comment]
@StephenWakely  No, each pod has a different persistent volume.

**Comment by yalinglee** [comment]
We have also observed the same errors with the S3 sink while running Vector 0.35.0: 
```
thread 'vector-worker' panicked at 'Reader encountered unrecoverable error: Io { source: Os { code: 2, kind: NotFound, message: "No such file or directory" } }', /project/lib/vector-buffers/src/topology/channel/receiver.rs:59:33
```
In our case, the `data_dir` is also pointing to a persistent volume in EKS, and each pod has its own dedicated volume since we use StatefulSets.

**Comment by zaldnoay** [comment]
We also encountered this problem, and there was nothing abnormal in the Journald. Very strange question, I'm not sure if it has anything to do with the kernel or file system.
```
thread 'vector-worker' panicked at /project/lib/vector-buffers/src/topology/channel/receiver.rs:59:33:
Reader encountered unrecoverable error: Io { source: Os { code: 2, kind: NotFound, message: "No such file or directory" } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-09-08T22:30:18.908466Z ERROR sink{component_kind="sink" component_id=gcp_vevct component_type=gcp_cloud_storage}: vector::topology: An error occurred that Vector couldn't handle: the task panicked and was aborted.
```

**Comment by trahim** [comment]
We also are having this issue, EKS, PV.

**Comment by satellite-no** [comment]
Hey all,

Wanted to pop in and say I'm seeing this issue as well happened to me on 4 or 5 nodes twice in the last two days.  I have a vector sink and the aws_s3 sink.  This is also running on ec2 nodes (no containers) with mounted EBS volumes.

**Comment by trahim** [comment]
I wanted to add some more info here, since moving from the disk buffer to memory we have had no issues, exactly the same config but removing the disk buffer config.

**Comment by nullbyte-dev** [comment]
Hi all!

+1 to this issue, encountered the same error with aws_s3_sink + disk buffers.
Setup: Kubernetes, STS with Persistent Volumes, Vector in Aggregator mode.
