### ISSUE TITLE
Flakey test `test_buffering` on Windows

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#4439]
Failure: https://github.com/timberio/vector/pull/4437/checks?check_run_id=1222218702

```
failures:

---- test_buffering stdout ----
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `20`,
 right: `10`', tests\buffering.rs:132:9
stack backtrace:
   0:     0x7ff788c9d56f - backtrace::backtrace::trace_unsynchronized
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1:     0x7ff788c9d56f - std::sys_common::backtrace::_print_fmt
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:78
   2:     0x7ff788c9d56f - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:59
   3:     0x7ff788cbf55b - core::fmt::write
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libcore\fmt\mod.rs:1069
   4:     0x7ff78510a89c - std::io::Write::write_fmt<test::helpers::sink::Sink>
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\src\libstd\io\mod.rs:1504
   5:     0x7ff788c8f288 - std::io::impls::{{impl}}::write_fmt<Write>
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\io\impls.rs:156
   6:     0x7ff788ca0b1c - std::sys_common::backtrace::_print
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:62
   7:     0x7ff788ca0b1c - std::sys_common::backtrace::print
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\sys_common\backtrace.rs:49
   8:     0x7ff788ca0b1c - std::panicking::default_hook::{{closure}}
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:198
   9:     0x7ff788ca06fe - std::panicking::default_hook
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:215
  10:     0x7ff788ca1307 - std::panicking::rust_panic_with_hook
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:511
  11:     0x7ff788ca0e8f - std::panicking::begin_panic_handler
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:419
  12:     0x7ff788ca0dfc - std::panicking::begin_panic_fmt
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libtest\lib.rs:475
  38:     0x7ff7851365b6 - test::run_test
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libtest\lib.rs:505
  39:     0x7ff785120a27 - test::run_tests
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libtest\lib.rs:284
  40:     0x7ff785120a27 - test::console::run_tests_console
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libtest\console.rs:280
  41:     0x7ff785132001 - test::test_main
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libtest\lib.rs:120
  42:     0x7ff785133992 - test::test_main_static
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libtest\lib.rs:139
  43:     0x7ff7850d5458 - buffering::test_buffering
  44:     0x7ff7850e18db - std::rt::lang_start::{{closure}}<()>
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\src\libstd\rt.rs:67
  45:     0x7ff788ca162a - std::rt::lang_start_internal::{{closure}}
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\rt.rs:52
  46:     0x7ff788ca162a - std::panicking::try::do_call
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:331
  47:     0x7ff788ca162a - std::panicking::try
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panicking.rs:274
  48:     0x7ff788ca162a - std::panic::catch_unwind
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\panic.rs:394
  49:     0x7ff788ca162a - std::rt::lang_start_internal
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\/src\libstd\rt.rs:51
  50:     0x7ff7850e18b3 - std::rt::lang_start<()>
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\src\libstd\rt.rs:67
  51:     0x7ff7850d5480 - main
  52:     0x7ff788ea52c4 - invoke_main
                               at D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  53:     0x7ff788ea52c4 - __scrt_common_main_seh
                               at D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  54:     0x7ffa62fd7974 - BaseThreadInitThunk
  55:     0x7ffa656aa271 - RtlUserThreadStart


failures:
    test_buffering
```

**Comment by jszwedko** [comment]
Closing since test doesn't exist anymore.
