### ISSUE TITLE
Cannot use file watching feature if wasm is enabled

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#5106]
Discovered during the course of #4809 

When `transform-wasm` is compiled in (and consequently `src/wasm`), it looks like SIGHUPs result in panics in the WASM code even if a `wasm` transform is not being used.

This causes the file watcher tests to fail. For example:

```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', /home/jesse/.cargo/git/checkouts/lucet-d29c7ec0f6d2e0d4/b1863da/lucet-runtime/lucet-runtime-internals/src/vmctx.rs:457:20
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::panicking::panic
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:50
   3: lucet_runtime_internals::vmctx::instance_from_vmctx
             at /home/jesse/.cargo/git/checkouts/lucet-d29c7ec0f6d2e0d4/b1863da/lucet-runtime/lucet-runtime-internals/src/vmctx.rs:457
   4: lucet_runtime_internals::vmctx::Vmctx::from_raw
             at /home/jesse/.cargo/git/checkouts/lucet-d29c7ec0f6d2e0d4/b1863da/lucet-runtime/lucet-runtime-internals/src/vmctx.rs:124
   5: raise
             at ./src/wasm/hostcall/mod.rs:124
   6: nix::sys::signal::raise
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.16.1/src/sys/signal.rs:693
   7: vector::config::watcher::raise_sighup
             at ./src/config/watcher.rs:96
   8: vector::config::watcher::spawn_thread::{{closure}}
             at ./src/config/watcher.rs:59
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'config::watcher::tests::file_update' panicked at 'Test timed out', src/config/watcher.rs:150:13
stack backtrace:
   0: std::panicking::begin_panic
             at /home/jesse/.rustup/toolchains/1.47.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:497
   1: vector::config::watcher::tests::file_update::{{closure}}
             at ./src/config/watcher.rs:150
   2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/jesse/.rustup/toolchains/1.47.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:79
   3: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::{{closure}}
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:131
   4: tokio::coop::with_budget::{{closure}}
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:127
   5: std::thread::local::LocalKey<T>::try_with
             at /home/jesse/.rustup/toolchains/1.47.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:265
   6: std::thread::local::LocalKey<T>::with
             at /home/jesse/.rustup/toolchains/1.47.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:241
   7: tokio::coop::with_budget
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:120
   8: tokio::coop::budget
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:96
   9: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:131
  10: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:213
  11: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/macros/scoped_tls.rs:63
  12: tokio::runtime::basic_scheduler::enter
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:213
  13: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:123
  14: tokio::runtime::Runtime::block_on::{{closure}}
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:444
  15: tokio::runtime::context::enter
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/context.rs:72
  16: tokio::runtime::handle::Handle::enter
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:76
  17: tokio::runtime::Runtime::block_on
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:441
  18: vector::config::watcher::tests::file_update
             at ./src/config/watcher.rs:139
  19: vector::config::watcher::tests::file_update::{{closure}}
             at ./src/config/watcher.rs:139
  20: core::ops::function::FnOnce::call_once
             at /home/jesse/.rustup/toolchains/1.47.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
  21: core::ops::function::FnOnce::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test config::watcher::tests::file_update ... FAILED
```

But also using `vector --watch-config` shows the same panic when the watched config is written to:

```
RUST_BACKTRACE=1 ./target/debug/vector --config /tmp/ecs.toml --watch-config /tmp/ecs.toml 2>&1 | tee /tmp/tmp.log
Nov 18 21:58:53.179  INFO vector::app: Log level is enabled. level="info"
Nov 18 21:58:53.179  INFO vector::config::watcher: Creating configuration file watcher.
Nov 18 21:58:53.180  INFO vector::config::watcher: Watching configuration files.
Nov 18 21:58:53.180  INFO vector::app: Loading configs. path=["/tmp/ecs.toml"]
Nov 18 21:58:53.197  INFO vector::topology: Running healthchecks.
Nov 18 21:58:53.197  INFO vector::topology: Starting source. name="my_source"
Nov 18 21:58:53.198  INFO vector::topology: Starting sink. name="my_sink"
Nov 18 21:58:53.198  INFO vector::topology::builder: Healthcheck: Passed.
Nov 18 21:58:53.198  INFO vector: Vector has started. version="0.11.0" git_version="v0.9.0-1426-g2f51841" released="Wed, 18 Nov 2020 20:19:09 +0000" arch="x86_64"
Nov 18 21:58:53.202 ERROR source{component_kind="source" component_name=my_source component_type=aws_ecs_metrics}: vector::internal_events::aws_ecs_metrics: HTTP request processing error. url=http://localhost:9080/v3/task/stats error=error trying to connect: tcp connect error: Connection refused (os error 111)
Nov 18 21:58:57.011  INFO vector::config::watcher: Configuration file changed.
[/home/jesse/.cargo/git/checkouts/lucet-d29c7ec0f6d2e0d4/b1863da/lucet-runtime/lucet-runtime-internals/src/vmctx.rs:457] vmctx as usize = 1
[/home/jesse/.cargo/git/checkouts/lucet-d29c7ec0f6d2e0d4/b1863da/lucet-runtime/lucet-runtime-internals/src/vmctx.rs:458] instance_heap_offset() = 4096
thread '<unnamed>' panicked at 'attempt to subtract with overflow', /home/jesse/.cargo/git/checkouts/lucet-d29c7ec0f6d2e0d4/b1863da/lucet-runtime/lucet-runtime-internals/src/vmctx.rs:459:20
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::panicking::panic
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:50
   3: lucet_runtime_internals::vmctx::instance_from_vmctx
             at /home/jesse/.cargo/git/checkouts/lucet-d29c7ec0f6d2e0d4/b1863da/lucet-runtime/lucet-runtime-internals/src/vmctx.rs:459
   4: lucet_runtime_internals::vmctx::Vmctx::from_raw
             at /home/jesse/.cargo/git/checkouts/lucet-d29c7ec0f6d2e0d4/b1863da/lucet-runtime/lucet-runtime-internals/src/vmctx.rs:124
   5: raise
             at ./src/wasm/hostcall/mod.rs:129
   6: nix::sys::signal::raise
             at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.16.1/src/sys/signal.rs:693
   7: vector::config::watcher::raise_sighup
             at ./src/config/watcher.rs:96
   8: vector::config::watcher::spawn_thread::{{closure}}
             at ./src/config/watcher.rs:59
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Again, the config doesn't mention the `wasm` transform:

```toml
[sources.my_source]
  type = "aws_ecs_metrics"
  endpoint = "http://localhost:9080/v3"
  version = "v3"

[sinks.my_sink]
  type = "console"
  inputs = ["my_source"]
  encoding.codec = "json"
```

The end result is that the file is never reloaded.

I spent some time digging into this with @Hoverbear but we weren't able to find any smoking guns. We thought we might try upgrading lucet first to see if that fixes anything. It's not a drop-in upgrade though, so we'll need to change some things as part of upgrading.

**Comment by Hoverbear** [comment]
I was speaking to @jamtur01 about this today and I suspect this problem will get resolved when we moved over to wasmtime as we'd previously discussed doing. If not, we might need to work with upstream to find a way to include our signals in the lucet overrides.

**Comment by jszwedko** [comment]
Closing since we dropped wasm support #8036
