### ISSUE TITLE
Flakey `sinks::file::tests::reopening` on OSX

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#5154]
Spotted here first: https://github.com/timberio/vector/pull/5148/checks?check_run_id=1433473109#step:10:1354

```
thread 'main' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
 [
     "zsobrpSSxG",
     "DazlqibjRu",
     "BZgp7DSTdK",
     "Cn9JUIahyx",
     "JommtSLdRt",
     "c2kgGIbzh8",
     "CyHfeWWXrZ",
     "n2gYfwb1aa",
     "emB4oFljHg",
     "niBQg3LG8k",
     "4QjXiayeEx",
     "3t6Fnv3eLG",
     "4ddlizPeIE",
     "mw6GTrSMDd",
     "c1TTSQPBv5",
     "CTrbpqYPqU",
     "UWzYmZ2xO4",
     "CG4ObzN9qF",
     "svFawwBwrf",
     "Z4RS3JDIE3",
     "ejGphSwiRN",
     "rebT5SbvVj",
     "SgrIMKsVsW",
     "t7Q0lioJJA",
     "Y80Vs36L8V",
     "P6yUcPw4Hw",
     "ywolqs0KBS",
     "7rBvTi3uwJ",
     "dmrqV10dbR",
     "OoHsuwjRjU",
     "1oIrhGdGoc",
     "WWJSNvKup7",
     "X0UF9x3ux7",
     "l3opL9Zt63",
     "tXeNhoKkxL",
     "hOw7kKhyss",
     "ydWKeYE3fX",
     "GdQyV9WPMa",
     "NiuwdYPvEZ",
     "a8iubJ2uHr",
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
  36:        0x109a210aa - test::__rust_begin_short_backtrace::h3525a66645c5bfc7
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/test/src/lib.rs:517
  37:        0x109a1f91e - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hb53c7c20f4b697da
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/boxed.rs:1042
  38:        0x109a1f91e - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h0f88e6632cbcaf45
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:308
  39:        0x109a1f91e - std::panicking::try::do_call::h176cd5bbf9c3e233
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373
  40:        0x109a1f91e - std::panicking::try::h9e191965ecb064f2
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337
  41:        0x109a1f91e - std::panic::catch_unwind::he0e9a2bd3a4985c5
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379
  42:        0x109a1f91e - test::run_test_in_process::h9a942859b5f42741
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/test/src/lib.rs:544
  43:        0x109a1f91e - test::run_test::run_test_inner::{{closure}}::h2b2c6792a791ad99
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/test/src/lib.rs:450
  44:        0x109a1f139 - test::run_test::run_test_inner::h3856e253b6426b3d
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/test/src/lib.rs:475
  45:        0x109a1d983 - test::run_test::hdd86b566f313ab11
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/test/src/lib.rs:505
  46:        0x109a0bfa3 - test::run_tests::h00e274117e64a04a
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/test/src/lib.rs:284
  47:        0x109a0bfa3 - test::console::run_tests_console::hf149f97a1d7624c0
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/test/src/console.rs:280
  48:        0x109a19e9b - test::test_main::he7b24900c0ca042d
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/test/src/lib.rs:120
  49:        0x109a1b366 - test::test_main_static::hef44138924533595
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/test/src/lib.rs:139
  50:        0x106b3abe8 - vector::main::h692cdbc22358d10f
  51:        0x10834e42e - core::ops::function::FnOnce::call_once::ha055c42c5e97c687
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
  52:        0x108e459b1 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9bec604d1b780e08
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:137
  53:        0x1068f8c44 - std::rt::lang_start::{{closure}}::h8458b95f385cbe94
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/rt.rs:66
  54:        0x10bf25c00 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h8a9b574793342aba
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:259
  55:        0x10bf25c00 - std::panicking::try::do_call::h4f96def3e784cc72
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373
  56:        0x10bf25c00 - std::panicking::try::h852a41061a270947
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337
  57:        0x10bf25c00 - std::panic::catch_unwind::h1c1a28455dde417c
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379
  58:        0x10bf25c00 - std::rt::lang_start_internal::hd0c760d47f593c0a
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/rt.rs:51
  59:        0x1068f8c21 - std::rt::lang_start::hb1c7b95f697ea011
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/rt.rs:65
  60:        0x106b3ac62 - _main
test sinks::file::tests::reopening ... FAILED
```

**Comment by jszwedko** [comment]
Closing to let flakey tests bubble back up.
