### ISSUE TITLE
Flakey `sources::file::tests::test_fair_reads` on OSX

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#5336]
Example failure: https://github.com/timberio/vector/pull/5332/checks?check_run_id=1486703628#step:8:5258

```
test sources::file::tests::test_fair_reads ... Dec 02 14:52:23.378  INFO vector::sources::file: Starting file server. include=["/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/.tmptjZJLy/*"] exclude=[]
Dec 02 14:52:24.022  WARN file_server: vector::internal_events::file::source: Currently ignoring file too small to fingerprint. path="/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/.tmptjZJLy/checkpoints.json"
Dec 02 14:52:24.030  INFO file_server: vector::internal_events::file::source: Found new file to watch. path="/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/.tmptjZJLy/z_older_file"
Dec 02 14:52:24.030  INFO file_server: vector::internal_events::file::source: Found new file to watch. path="/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/.tmptjZJLy/a_newer_file"
thread 'main' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
 [
     Bytes(
         b"hello i am the old file",
     ),
     Bytes(
         b"and i am the new file",
     ),
>    Bytes(
>        b"i have been around a while",
>    ),
>    Bytes(
>        b"this should be interleaved with the old one",
>    ),
>    Bytes(
>        b"you can read newer files at the same time",
>    ),
>    Bytes(
>        b"which is fine because we want fairness",
>    ),
 ]

', src/sources/file.rs:1310:9
stack backtrace:
   0:        0x108e76d34 - std::backtrace_rs::backtrace::libunwind::trace::h6df1416181381e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:        0x108e76d34 - std::backtrace_rs::backtrace::trace_unsynchronized::h792524067a83cded
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:        0x108e76d34 - std::sys_common::backtrace::_print_fmt::he614892186429f3f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:        0x108e76d34 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcfc48256a5ab8835
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:        0x108e9db80 - core::fmt::write::haf3903118f694c48
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:        0x108e6da66 - std::io::Write::write_fmt::h7385463ac87804ed
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:        0x108e78e3f - std::sys_common::backtrace::_print::ha64a9740ea6183e6
  57:        0x108e79864 - std::panic::catch_unwind::h1ebce9249c33ec53
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382
  58:        0x108e79864 - std::rt::lang_start_internal::hd38bb63f9540b327
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:51
  59:        0x1038a7c81 - std::rt::lang_start::h838abe6dca61ec31
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:65
  60:        0x103b09db2 - _main
Dec 02 14:52:24.677  WARN vector::internal_events::file::source: Failed writing checkpoints. error=Os { code: 2, kind: NotFound, message: "No such file or directory" }
FAILED
```

**Comment by jszwedko** [comment]
Closing to let flakey tests bubble back up.
