### ISSUE TITLE
Review API cue data

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#5403]
The [API cue data](https://github.com/timberio/vector/blob/master/docs/reference/api.cue) needs a review to ensure its accuracy. Please open a pull request and correct any mistakes.

**Comment by leebenson** [comment]
@binarylogic, there are some aspects of the [API docs](https://vector.dev/docs/reference/api/) I'd like to fix related to this issue, but I'm currently blocked by this:

```
➜  scripts git:(leebenson/api-docs) ✗ ./generate.rb

--------------------------------------------------------------------------------
#### Loading data...
---> Loaded /Users/leebenson/dev/timberio/vector-website/scripts/../.meta
---> Loaded /Users/leebenson/dev/timberio/vector-website/scripts/../docs
---> Loaded /Users/leebenson/dev/timberio/vector-website/scripts/../guides
---> Loaded /Users/leebenson/dev/timberio/vector-website/scripts/../vector/docs/highlights
---> Loaded /Users/leebenson/dev/timberio/vector-website/scripts/../src/pages
---> Loaded /Users/leebenson/dev/timberio/vector-website/scripts/../blog
Traceback (most recent call last):
    5: from ./generate.rb:55:in `<main>'
    4: from /Users/leebenson/dev/timberio/vector-generate/lib/vector-generate/data_loaders/reference_loader.rb:44:in `load!'
    3: from /Users/leebenson/dev/timberio/vector-generate/lib/vector-generate/data_loaders/reference_loader.rb:44:in `each'
    2: from /Users/leebenson/dev/timberio/vector-generate/lib/vector-generate/data_loaders/reference_loader.rb:45:in `block in load!'
    1: from /Users/leebenson/dev/timberio/vector-generate/lib/vector-generate/data_loaders/reference_loader.rb:70:in `transform_component'
/Users/leebenson/dev/timberio/vector-generate/lib/vector-generate/data_loaders/reference_loader.rb:70:in `fetch': key not found: "platforms" (KeyError)
```

Am I missing a step?

**Comment by leebenson** [comment]
I've put this into the backlog, as I'm still blocked on the above.

**Comment by jszwedko** [comment]
Closing since this seems to be up-to-date now.
