### ISSUE TITLE
Check if Rust and Cue is installed before running `make build`

### ISSUE THREAD

**Issue by f34nk** [vectordotdev/vector#8146]
### Problem

While following the "install from source" documentation ([here](https://vector.dev/docs/setup/installation/manual/from-source/)) the Makefile did not check if `rustc` or `cue` binary is available.

### This is what I experienced:

Running `make build` I get this error:
``` 
make: cargo: No such file or directory --> install Rust
```

So solving this is quite obvious.

However, when the build succeeds and I try to run `RUST_BACKTRACE=1 make test-vrl`  I get this error:
```
Finished dev [unoptimized + debuginfo] target(s) in 1.15s
     Running `***/vector/target/debug/vrl-tests`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)', lib/vrl/tests/src/docs.rs:80:48
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1355:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1037:23
   4: vrl_tests::docs::tests
             at ./src/docs.rs:80:9
   5: vrl_tests::main
             at ./src/main.rs:83:16
   6: core::ops::function::FnOnce::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
make: *** [test-vrl] Error 101
```

From this error, it is not obious that `cue` is missing.

Installing `cue` makes this error go away.

### Proposal

Have a check in the Makefile if binaries are installed.
This way, `make build` will fail early and also give a suggestion how to solve the problem.

From the `Makefile`
```
##@ Building
.PHONY: build
build: check-build-tools
build: export CFLAGS += -g0 -O3
build: ## Build the project in release mode (Supports `ENVIRONMENT=true`)
	${MAYBE_ENVIRONMENT_EXEC} cargo build --release --no-default-features --features ${DEFAULT_FEATURES}
	${MAYBE_ENVIRONMENT_COPY_ARTIFACTS}
...
.PHONY: check-build-tools
check-build-tools:
ifeq (, $(shell which rustc))
	$(error "Please install Rust: https://www.rust-lang.org/tools/install")
endif
ifeq (, $(shell which cue))
	$(error "Please install Cue: https://cuelang.org/docs/install/")
endif
```

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/8147
