### ISSUE TITLE
Vector crash: `ServiceSink service sender dropped`

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#8669]
A user running a debug build of 0.14.0 ran into a crash in the `aws_s3` sink after `ctrl-C`ing:

```
thread 'tokio-runtime-worker' panicked at 'ServiceSink service sender dropped.', src/sinks/util/sink.rs:474:33
stack backtrace:
   0:     0x564d4a2a93d0 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x564d4a2a93d0 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x564d4a2a93d0 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x564d4a2a93d0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x564d4a31680f - core::fmt::write::h3b84512577ca38a8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x564d4a29d522 - std::io::Write::write_fmt::h465f8feea02e2aa1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x564d4a2ad215 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x564d4a2ad215 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x564d4a2ad215 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x564d4a2accc3 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x564d4a2ad95d - std::panicking::rust_panic_with_hook::hb89f5f19036e6af8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
  11:     0x564d47de7213 - std::panicking::begin_panic::{{closure}}::h085fe9f27aab10f8
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:520:9
  12:     0x564d47db98e9 - std::sys_common::backtrace::__rust_end_short_backtrace::he2dcee0fb89ef9ba
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x564d47de7149 - std::panicking::begin_panic::hdec36c645caf136b
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
  14:     0x564d42320f59 - vector::sinks::util::sink::ServiceSink<S,Request>::poll_complete::h748f94949d35d556
                               at /home/jesse/workspace/vector/src/sinks/util/sink.rs:474:33
  15:     0x564d4228cd39 - <vector::sinks::util::sink::PartitionBatchSink<S,B,K> as futures_sink::Sink<vector::sinks::util::EncodedEvent<<B as vector::sinks::util::batch::Batch>::Input>>>::poll_f
lush::h5d1896d9764e73f1
                               at /home/jesse/workspace/vector/src/sinks/util/sink.rs:342:20
  16:     0x564d42279204 - <vector::sinks::util::sink::PartitionBatchSink<S,B,K> as futures_sink::Sink<vector::sinks::util::EncodedEvent<<B as vector::sinks::util::batch::Batch>::Input>>>::poll_r
eady::h4353b436b4580373
                               at /home/jesse/workspace/vector/src/sinks/util/sink.rs:236:19
  17:     0x564d42031fc4 - futures_util::sink::with_flat_map::WithFlatMap<Si,Item,U,St,F>::try_empty_stream::he93b4ff01d1cb85a
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/sink/with_flat_map.rs:61:23
  18:     0x564d42025e5b - <futures_util::sink::with_flat_map::WithFlatMap<Si,Item,U,St,F> as futures_sink::Sink<U>>::poll_ready::h47f3621b8cb64c53
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/sink/with_flat_map.rs:107:9
  19:     0x564d43e6d731 - <futures_util::sink::map_err::SinkMapErr<Si,F> as futures_sink::Sink<Item>>::poll_ready::h20cbd5ff56a73960
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/sink/map_err.rs:38:9
  20:     0x564d410763f3 - futures_sink::if_alloc::<impl futures_sink::Sink<Item> for alloc::boxed::Box<S>>::poll_ready::hff54f818bc6b76c3
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.15/src/lib.rs:214:13
  21:     0x564d41578435 - <futures_util::stream::stream::forward::Forward<St,Si,Item> as core::future::future::Future>::poll::h37ebbb75bc76cb2a
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/stream/stream/forward.rs:55:24
  22:     0x564d431eb03e - <futures_util::stream::stream::Forward<St,Si> as core::future::future::Future>::poll::h328b0fe18fc9457f
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/lib.rs:93:13
  23:     0x564d426ab9ff - vector::sinks::VectorSink::run::{{closure}}::h509a1690e6779d7e
                               at /home/jesse/workspace/vector/src/sinks/mod.rs:104:33
  24:     0x564d4353dabd - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h8953223d88b2ce2e
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  25:     0x564d440477ba - vector::topology::builder::build_pieces::{{closure}}::{{closure}}::hbeee7425899149eb
                               at /home/jesse/workspace/vector/src/topology/builder.rs:227:13
  26:     0x564d435069a4 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h044707dade67e6d8
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  27:     0x564d4395d7ec - <vector::topology::task::Task as core::future::future::Future>::poll::h766fc17f08d1aac4
                               at /home/jesse/workspace/vector/src/topology/task.rs:56:9
  28:     0x564d412e199f - <std::panic::AssertUnwindSafe<F> as core::future::future::Future>::poll::h8011df98d3b91f37
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:361:9
  29:     0x564d427528de - <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}::ha26554f78bcdf40c
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/future/future/catch_unwind.rs:36:42
  30:     0x564d41059dec - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hdcee4c7eba3b788a
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  31:     0x564d427dbc6f - std::panicking::try::do_call::hc75afef46a3b4866
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  32:     0x564d4299765d - __rust_try
  33:     0x564d427d16cf - std::panicking::try::h5d6e739b38e1d08d
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  34:     0x564d41085dbb - std::panic::catch_unwind::h45ba95db23da0d51
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  35:     0x564d42752806 - <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::hc99faa194bf22415
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/future/future/catch_unwind.rs:36:9
  36:     0x564d41baceab - vector::topology::handle_errors::{{closure}}::h0f83b489eb21bd3a
                               at /home/jesse/workspace/vector/src/topology/mod.rs:779:5
  37:     0x564d4353df35 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h8a25faeba62a0947
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  38:     0x564d434e64e9 - <tracing_futures::Instrumented<T> as core::future::future::Future>::poll::h1784f61b2b3638f0
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-futures-0.2.5/src/lib.rs:283:9
  39:     0x564d434771f8 - tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}::h19cab60f16363353
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/task/core.rs:235:17
  40:     0x564d43bc279f - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hc314b742a599d636
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/loom/std/unsafe_cell.rs:14:9
  41:     0x564d434746d5 - tokio::runtime::task::core::CoreStage<T>::poll::h6e12adb2d68ae025
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/task/core.rs:225:13
  42:     0x564d411ad84b - tokio::runtime::task::harness::poll_future::{{closure}}::hc6044076459b0c2d
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/task/harness.rs:422:23
  43:     0x564d4105911c - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h645ef1592aa3f441
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  44:     0x564d427db25f - std::panicking::try::do_call::h9f8feb3cb127c34e
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  45:     0x564d4299765d - __rust_try
  46:     0x564d427cf15f - std::panicking::try::h342d503f3f9a8f0b
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  47:     0x564d41086a6b - std::panic::catch_unwind::h86160905c891bf43
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  48:     0x564d41195a7e - tokio::runtime::task::harness::poll_future::h1409ab1dc7626079
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/task/harness.rs:409:19
  49:     0x564d411b5ab7 - tokio::runtime::task::harness::Harness<T,S>::poll_inner::ha0768d5fc661a5e4
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/task/harness.rs:89:9
  50:     0x564d411e2c4c - tokio::runtime::task::harness::Harness<T,S>::poll::h736c18d3b5ca5812
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/task/harness.rs:59:15
  51:     0x564d4342bb52 - tokio::runtime::task::raw::poll::h8f77e326bba69bb1
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/task/raw.rs:104:5
  52:     0x564d4881483f - tokio::runtime::task::raw::RawTask::poll::h040bccdfa167833c
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/task/raw.rs:66:18
  53:     0x564d48883651 - tokio::runtime::task::Notified<S>::run::h7cc67ead1eb18dc5
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/task/mod.rs:171:9
  54:     0x564d488b7622 - tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}::hf62f5c98db9bef3c
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/thread_pool/worker.rs:349:13
  55:     0x564d4887b05c - tokio::coop::with_budget::{{closure}}::h2ec1857b8bd3dd4c
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/coop.rs:106:9
  56:     0x564d48845058 - std::thread::local::LocalKey<T>::try_with::h2646c65d81c85fce
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  57:     0x564d4884422e - std::thread::local::LocalKey<T>::with::h5ad78814ae59beec
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  58:     0x564d488b7443 - tokio::coop::with_budget::h5ef86fa2813e1d41
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/coop.rs:99:5
  59:     0x564d488b7443 - tokio::coop::budget::h8d09af1172786bb7
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/coop.rs:76:5
  60:     0x564d488b7443 - tokio::runtime::thread_pool::worker::Context::run_task::haf6255746f69e730
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/thread_pool/worker.rs:348:9
  61:     0x564d488b6e8f - tokio::runtime::thread_pool::worker::Context::run::h19cd58f92f6627d4
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/thread_pool/worker.rs:318:24
  62:     0x564d488b6c93 - tokio::runtime::thread_pool::worker::run::{{closure}}::h695f06d56416ef72
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/thread_pool/worker.rs:303:17
  63:     0x564d48879bed - tokio::macros::scoped_tls::ScopedKey<T>::set::h91ead2e38928c535
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/macros/scoped_tls.rs:61:9
  64:     0x564d488b6b73 - tokio::runtime::thread_pool::worker::run::h357c45fa9250a5e6
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/thread_pool/worker.rs:300:5
  65:     0x564d488b6a3b - tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}::h0958e6b090812a28
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/thread_pool/worker.rs:279:45
  66:     0x564d488867ff - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h20c122390d6b0d90
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/blocking/task.rs:42:21
  67:     0x564d487e5610 - tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}::h1ad23b8f1c2b3080
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/task/core.rs:235:17
  68:     0x564d488e7e1e - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hd271c819e83a2ab3
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/loom/std/unsafe_cell.rs:14:9
  69:     0x564d487e4b98 - tokio::runtime::task::core::CoreStage<T>::poll::h014c35e2fc01c78b
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/task/core.rs:225:13
  70:     0x564d4886ecae - tokio::runtime::task::harness::poll_future::{{closure}}::h7a56ab34070ba47c
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/task/harness.rs:422:23
  71:     0x564d488a81f3 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf7bd453f0ade928b
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  72:     0x564d488378c2 - std::panicking::try::do_call::h7cb62d2d67719124
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  73:     0x564d48843ddd - __rust_try
  74:     0x564d48836d5a - std::panicking::try::ha7ec7408be225c51
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  75:     0x564d488a964b - std::panic::catch_unwind::hb930e473e952bbef
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  76:     0x564d4886b47e - tokio::runtime::task::harness::poll_future::h10ddd591a9c2de15
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/task/harness.rs:409:19
  77:     0x564d488643c3 - tokio::runtime::task::harness::Harness<T,S>::poll_inner::ha9d09b293becc2c8
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/task/harness.rs:89:9
  78:     0x564d48862c1c - tokio::runtime::task::harness::Harness<T,S>::poll::h3500ffa3467d052b
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/task/harness.rs:59:15
  79:     0x564d48814bc2 - tokio::runtime::task::raw::poll::hd315e1fd554108e1
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/task/raw.rs:104:5
  80:     0x564d4881483f - tokio::runtime::task::raw::RawTask::poll::h040bccdfa167833c
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/task/raw.rs:66:18
  81:     0x564d488835e1 - tokio::runtime::task::Notified<S>::run::h5b114330dcbc9958
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/task/mod.rs:171:9
  82:     0x564d488a6fc6 - tokio::runtime::blocking::pool::Inner::run::h1d105ad67ea4efcb
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/blocking/pool.rs:278:17
  83:     0x564d488a6d69 - tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::h0e114b3a459486fa
                               at /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/blocking/pool.rs:258:17
  84:     0x564d487d236c - std::sys_common::backtrace::__rust_begin_short_backtrace::haad90d667a525a6b
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  85:     0x564d488ce811 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hb5a186dc48edf405
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:474:17
  86:     0x564d488a8071 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h7861b1fc2942803d
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  87:     0x564d48837cbc - std::panicking::try::do_call::hd9b9927186a8ce00
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  88:     0x564d48843ddd - __rust_try
  89:     0x564d48836e77 - std::panicking::try::hbaa31de264ce8f4e
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  90:     0x564d488a9711 - std::panic::catch_unwind::hde7590f1830d8cdb
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  91:     0x564d488ce611 - std::thread::Builder::spawn_unchecked::{{closure}}::hcf6c0bf3145e819c
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:473:30
  92:     0x564d4880184f - core::ops::function::FnOnce::call_once{{vtable.shim}}::h04d693f203193a91
                               at /home/jesse/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  93:     0x564d4a2bd16a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc444a77f8dd8d825
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/alloc/src/boxed.rs:1546:9
  94:     0x564d4a2bd16a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8b68a0a9a2093dfc
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/alloc/src/boxed.rs:1546:9
  95:     0x564d4a2bd16a - std::sys::unix::thread::Thread::new::thread_start::hb95464447f61f48d
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys/unix/thread.rs:71:17
  96:     0x7f8c152da40b - start_thread
  97:     0x7f8c14ad10bf - __GI___clone
  98:                0x0 - <unknown>
```

**Comment by jszwedko** [comment]
Closing as stale. I'm not sure we ever reproduced this issue.
